cordada/lib-cl-sii-python

- cl_sii/extras/mm_fields.py
- tests/test_extras_mm_fields.py
Marshmallow field for a DTE's "tipo DTE".
> extras: add Marshmallow field for a DTE's "tipo DTE"

- cl_sii/libs/encoding_utils.py
- tests/test_libs_encoding_utils.py
Includes these functions:
- `clean_base64`
- `decode_base64_strict`
- `validate_base64`
> libs: add module `encoding_utils`

- cl_sii/libs/mm_utils.py
- requirements/base.txt
- requirements/test.txt
- setup.py
- Add reasonable version upper-bound for each required package.
- Update 'marshmallow'.
- Update 'lxml'.
- Update 'defusedxml' .
- Update all test requirements.
> Requirements: updates and package upper-bounds

- cl_sii/dte/data_models.py
- tests/test_dte_data_models.py
CC @yaselc @jtrh @CamilaAtenas
> dte.data_models: fix bug in `DteDataL2`

- cl_sii/dte/parse.py
- tests/test_data/sii-dte/DTE--76354771-K--33--170--cleaned-mod-empty-emails.xml
- tests/test_dte_parse.py
> dte.parse: fix edge case in `parse_dte_xml`

- cl_sii/libs/dataclass_utils.py
- tests/test_libs_dataclass_utils.py
Include function and mixin for dataclass instances "deep comparison".
> libs: add module `dataclass_utils`

- cl_sii/dte/constants.py
- cl_sii/dte/data_models.py
- cl_sii/rcv/constants.py
- tests/test_dte_constants.py
- tests/test_dte_data_models.py
- `data_models`: improve `DteDataL1`'s properties of "vendedor/comprador/deudor".
- `constants`: add enum member to `TipoDteEnum` for "Liquidación-Factura Electrónica" (43).
> dte: misc data models and enum improvements

- cl_sii/dte/constants.py
- cl_sii/dte/data_models.py
- tests/test_dte_data_models.py
Resolves: https://github.com/fyndata/lib-cl-sii-python/issues/79
> dte: Allow negative 'monto_total' when DTE type is 'liquidación-factura electrónica'

- .deepsource.toml
File auto-generated by the tool.
> add config file for "deepsource"

- .deepsource.toml
Set maximum line length so that it is consistent with the value configured for Flake8.
> update config file for "deepsource"

- cl_sii/extras/mm_fields.py
- tests/test_extras_mm_fields.py
Marshmallow field for RCV's "periodo tributario".
> extras.mm_fields: add `RcvPeriodoTributarioField`

- requirements/base.txt
- requirements/extras.txt
- requirements/release.txt
- requirements/test.txt
- setup.py
Significant packages that were updated:
- `cryptography`
- `Django` (extras)
- `djangorestframework` (extras)
- `lxml`
- `pytz`
Packages no longer needed: no.
Similar to https://github.com/fyntex/lib-cl-sii-api-python/pull/120
> requirements: several updates

- LICENSE
- README.rst
- cl_sii/contribuyente/constants.py
- cl_sii/dte/constants.py
- cl_sii/rcv/constants.py
- cl_sii/rut/constants.py
- docs/project-maintenance.rst
- setup.py
- References to repositories (self and others).
- References to other services (e.g. CircleCI).
- Author and contact information.
Analogous to https://github.com/fyntex/lib-cl-sii-api-python/commit/b604779 and https://github.com/fyntex/lib-cl-sii-api-python/commit/71fd5f7
> Update everything for Fyntex, the new owner

- cl_sii/cte/f29/parse_datos_obj.py
- tests/test_cte_f29_parse_datos_obj.py
Resolves: https://github.com/fyntex/lib-cl-sii-python/pull/103#discussion_r383877035
Resolves: https://github.com/fyntex/lib-cl-sii-python/pull/103#discussion_r383877269
> cte.f29.parser: Rename custom validator and deserializer parameters

- .bumpversion.cfg
- cl_sii/__init__.py
- cl_sii/dte/data_models.py
- cl_sii/rcv/data_models.py
- tests/test_dte_data_models.py
- (PR #112, 2020-04-14) data_models: make some fields optional
> Release v0.10.0.a2

- .github/dependabot.yml
Ref: [Keep all your packages up to date with Dependabot](https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/)
Ref: https://github.com/fyntex/meta/issues/14
> config: Add configuration for GitHub Dependabot

- cl_sii/libs/xml_utils.py
- requirements/base.txt
- setup.py
Changelog:
- 2.8.0 (2020-06-20)
https://github.com/XML-Security/signxml/blob/v2.8.0/Changes.rst#changes-for-v280-2020-06-20
- …
- 2.7.0 (2019-11-30)
https://github.com/XML-Security/signxml/blob/v2.8.0/Changes.rst#changes-for-v270-2019-11-30
Code diff: https://github.com/XML-Security/signxml/compare/v2.6.0...v2.8.0
Ref: https://github.com/fyntex/lib-cl-sii-python/issues/130
> requirements: update 'signxml'

- requirements/test.txt
- scripts/clean_dte_xml_file.py
(plus some dependencies)
Changelog:
- 3.8.4 (2020-10-02)
https://gitlab.com/pycqa/flake8/blob/3.8.4/docs/source/release-notes/3.8.4.rst
- …
- 3.8.0 (2020-05-11)
https://gitlab.com/pycqa/flake8/blob/3.8.4/docs/source/release-notes/3.8.0.rst
Code diff: https://gitlab.com/pycqa/flake8/compare/3.7.9...3.8.4
> requirements: Update 'flake8'

- .circleci/config.yml
Replace testing of versions 3.7.2 and 3.7.6 with 3.7.9.
> config: Update Python 3.7 version to 3.7.9

- requirements/test.txt
(plus some dependencies)
Changelog:
- 0.790 (2020-10-09):
http://mypy-lang.blogspot.com/2020/10/mypy-0790-released.html
Code diff: https://github.com/python/mypy/compare/v0.782...v0.790
> requirements: update 'mypy' (test)

- requirements/test.txt
Changelog:
- 3.20.1 (2020-10-09):
https://github.com/tox-dev/tox/blob/3.20.1/docs/changelog.rst#v3201-2020-10-09
- …
- 3.17.0 (2020-07-14):
https://github.com/tox-dev/tox/blob/3.20.1/docs/changelog.rst#v3170-2020-07-14
Code diff: https://github.com/tox-dev/tox/compare/3.16.1...3.20.1
> requirements: update 'tox' (test)

- requirements/extras.txt
- setup.py
Upgrade Django `2.2.10` -> `2.2.18` with fixes to some known vulnerabilities
- https://github.com/advisories/GHSA-fvgf-6h6h-3322
- https://github.com/advisories/GHSA-m6gj-h9gm-gw44
- https://github.com/advisories/GHSA-fr28-569j-53c4
Resolves #203
> requirements: Upgrade 'Django'

- requirements/extras.txt
- setup.py
Remove Django upper bound constraint, we have no specific reason or inconvenience to preserve this restriction
Resolves #225
> requirements: Remove Django upper bound constraint

- .bumpversion.cfg
- .circleci/config.yml
- HISTORY.rst
- cl_sii/__init__.py
- cl_sii/dte/data_models.py
- tests/test_dte_data_models.py
- (PR #228, 2021-06-29) config: Update Python version used in CI jobs to 3.8.10
- (PR #230, 2021-07-09) dte: Convert stdlib dataclass `DteXmlData` into pydantic dataclass
> Release v0.13.0

- .bumpversion.cfg
- HISTORY.rst
- cl_sii/__init__.py
- cl_sii/dte/data_models.py
- tests/test_dte_data_models.py
- (PR #234, 2021-08-09) dte: Convert stdlib dataclasses into pydantic dataclasses
- (PR #236, 2021-08-09) DteXmlData: Restore mistakenly deleted regression tests
> Release v0.14.0

- .bumpversion.cfg
- HISTORY.rst
- cl_sii/__init__.py
- cl_sii/rcv/data_models.py
- cl_sii/rut/constants.py
- cl_sii/rut/crypto_utils.py
- tests/test_libs_crypto_utils.py
- tests/test_rcv_data_models.py
- tests/test_rut_crypto_utils.py
- (PR #251, 2022-01-14) rcv: Convert stdlib dataclasses into pydantic dataclasses
- (PR #267, 2022-01-27) cl_sii.rut: Add method to get the RUT of the certificate holder
> Release v0.17.0

- .bumpversion.cfg
- .circleci/config.yml
- HISTORY.rst
- cl_sii/__init__.py
- requirements-dev.txt
- (PR #326, 2022-05-25) chore(requirements-dev): Update package `readme-renderer` to 35.0
- (PR #325, 2022-05-25) chore: Update Python to version 3.8.13
> Release v0.17.3

- .github/dependabot.yml
Ref: https://cordada.aha.io/features/TECHINFRA-111
Ref: https://github.com/cordada/infra/issues/40
> chore: Change Dependabot schedule interval from `weekly` to `monthly`

- .circleci/config.yml
- Makefile
- README.rst
- Add Make tasks `install-dev` and `install-deps-dev`.
- Update CI configuration.
- Update documentation.
Ref: https://cordada.aha.io/features/COMPCLDATA-113
> chore: Add Make tasks for installation

- .github/workflows/git-commit-lint.yaml
- commitlint.config.js
Ref: https://cordada.aha.io/features/PLATCORE-411
Ref: https://github.com/cordada/infra/issues/36
> chore: Add Git commit linter

- .bumpversion.cfg
- docs/project-maintenance.rst
- chore: Update Bumpversion configuration to be compliant with Commitlint.
- chore: Update project maintenance documentation for Git commit linter.
Ref: https://github.com/fyntex/lib-cl-sii-python/pull/359
> Update files for Git commit linter

- .github/workflows/super-linter.yaml
- .markdownlint.yaml
- README.md
- cl_sii/data/ref/factura_electronica/schemas-xml/README.md
- chore: Add CI configuration for Super-Linter.
- chore: Add Markdownlint configuration.
- fix: Fix errors reported by Markdown linter.
> Add Super-Linter

- .circleci/config.yml
Ref: https://cordada.aha.io/features/COMPCLDATA-130
> fix(deps): Workaround for CI issues related to `python-deps-sync-check`

- .github/workflows/dependency-review.yaml
Ref: https://cordada.aha.io/features/TECHINFRA-163
Ref: https://github.com/fyntex/lib-cl-sii-python/pull/422
> Improve GitHub Dependency Review

- .bumpversion.cfg
- HISTORY.md
- cl_sii/__init__.py
- (PR #452, 2023-03-09) fix(data.cte): Add JSON files to MANIFEST.in
> Release v0.22.1

- setup.py
Ref: https://github.com/fyntex/lib-cl-sii-python/pull/428
Resolves: https://github.com/fyntex/lib-cl-sii-python/pull/428#discussion_r1134591615
Resolves: https://github.com/fyntex/lib-cl-sii-python/pull/428#discussion_r1134591877
> Update minimum version of `signxml` to `3.1.0`

- .editorconfig
- .github/workflows/super-linter.yaml
- Run only for pull requests and pushes to main branches.
- To improve speed, only process changed files.
Ref: https://cordada.aha.io/requirements/TECHINFRA-192-19
Ref: https://cordada.aha.io/features/TECHINFRA-192
> Update Super-Linter configuration

- .bumpversion.cfg
- HISTORY.md
- cl_sii/__init__.py
- (PR #443, 2023-03-13) chore(deps-dev): Bump types-pytz from 2022.7.1.0 to 2022.7.1.2
- (PR #445, 2023-03-13) chore(deps-dev): Bump types-jsonschema from 4.17.0.3 to 4.17.0.6
- (PR #428, 2023-03-13) chore(deps): Bump signxml from 2.10.1 to 3.1.0
- (PR #444, 2023-03-13) chore(deps-dev): Bump types-pyopenssl from 23.0.0.2 to 23.0.0.4
- (PR #462, 2023-03-14) Update minimum version of `signxml` to `3.1.0`
- (PR #429, 2023-03-14) chore(deps): Bump importlib-metadata from 1.6.0 to 6.0.0
- (PR #463, 2023-03-29) Decrease Dependabot's open pull request limit to 5
- (PR #475, 2023-04-03) Update Editor Configuration
- (PR #474, 2023-04-04) Update Super-Linter configuration
- (PR #218, 2023-04-04)  Add data model for DTE Referencia
- (PR #461, 2023-04-04) Add contributing guidelines
> Release v0.23.0

- requirements-dev.in
- requirements-dev.txt
- [Software Repository](https://pypi.org/project/black/23.3.0/)
- [Release notes](https://github.com/psf/black/releases/tag/23.3.0)
- [Changelog](https://github.com/psf/black/blob/23.3.0/CHANGES.md#2330)
- [Commits](https://github.com/psf/black/compare/23.1.0...23.3.0)
> chore(deps): Update `black` from 23.1.0 to 23.3.0

- requirements.txt
- [Software Repository](https://pypi.org/project/django/3.2.20/)
- [Release notes](https://docs.djangoproject.com/en/3.2/releases/3.2.20/)
- [Commits](https://github.com/django/django/compare/3.2.17...3.2.20)
> chore(deps): Update `django` from 3.2.17 to 3.2.20

- requirements.in
- requirements.txt
- [Software Repository](https://pypi.org/project/pydantic/1.10.12/)
- [Release notes](https://github.com/pydantic/pydantic/releases/tag/v1.10.12)
- [Changelog](https://github.com/pydantic/pydantic/blob/v1.10.12/HISTORY.md#v11012-2023-07-24)
- [Commits](https://github.com/pydantic/pydantic/compare/v1.10.4...v1.10.12)
> chore(deps): Update `pydantic` from 1.10.4 to 1.10.12

- .bumpversion.cfg
- HISTORY.md
- cl_sii/__init__.py
- (PR #522, 2023-08-07) Enable Editor Configuration validation in Super-Linter
- (PR #523, 2023-08-08) chore(deps): Update `pydantic` from 1.10.4 to 1.10.12
- (PR #524, 2023-08-10) Fix type checking of Setuptools configuration
- (PR #521, 2023-08-10) chore: Bump cryptography from 41.0.2 to 41.0.3
- (PR #525, 2023-08-28) Add dependency groups to Dependabot configuration
- (PR #526, 2023-08-28) chore: Bump the production-dependencies group with 2 updates
> Release v0.23.2

- cl_sii/data/ref/factura_electronica/schemas-xml/.editorconfig
- tests/test_data/.editorconfig
Add specific EditorConfig files for the following directories:
- `cl_sii/data/ref/factura_electronica/schemas-xml/`
- `tests/test_data/`
> Fix errors reported by EditorConfig-Checker

- .bumpversion.cfg
- HISTORY.md
- src/cl_sii/__init__.py
- (PR #530, 2023-09-05) chore: Bump the development-dependencies group with 9 updates
- (PR #536, 2023-09-05) chore(deps): Update `typing-extensions` from 4.3.0 to 4.7.1
- (PR #538, 2023-09-06) Fix errors reported by EditorConfig-Checker
- (PR #537, 2023-09-06) Change Python project structure from Flat layout to Src layout
- (PR #539, 2023-09-07) Add Codecov repository upload token; update Codecov status badge
- (PR #540, 2023-09-14) Update pydantic from 1.10.12 to 2.3.0
> Release v0.23.3

- requirements.in
- requirements.txt
- setup.py
- src/tests/test_libs_xml_utils.py
- [Software Repository](https://pypi.org/project/lxml/5.1.0/)
- [Release notes](https://github.com/lxml/lxml/blob/lxml-5.1.0/CHANGES.txt#L5)
- [Changelog](https://github.com/lxml/lxml/blob/lxml-5.1.0/CHANGES.txt#L5)
- [Commits](https://github.com/lxml/lxml/compare/lxml-4.9.4...lxml-5.1.0)
> chore(deps): Update `lxml` from 4.9.4 to 5.1.0

- mypy.ini
- requirements.in
- requirements.txt
- setup.py
- src/cl_sii/extras/dj_filters.py
- src/tests/test_extras_dj_filters.py
- Add Filter class `RutFilter`.
- Add FilterSet class `SiiFilterSet`.
- TODO: Add tests.
Most of the code originates from an internal application (see commit 2e9ce461 of that application’s source code), and was originally written by Yasel Couce.
Jose Tomas Robles Hahn did some refactoring and made some minor improvements.
Ref: https://app.shortcut.com/cordada/story/8313
> extras: Add `RutFilter` for Django views and DRF views

- .bumpversion.cfg
- HISTORY.md
- src/cl_sii/__init__.py
- (PR #661, 2024-07-17) extras: Add `RutFilter` for Django views and DRF views
- (PR #662, 2024-07-17) extras: Add Django URL path converter for RUT and Tipo DTE
- (PR #663, 2024-07-17) extras: Add mapping of Django model fields to DRF serializer fields
- (PR #664, 2024-07-17) extras: Reformat source code of `.dj_filters`
> Release v0.31.0

- requirements-dev.txt
- [Software Repository](https://pypi.org/project/pip/24.2/)
- [Release notes](https://pip.pypa.io/en/stable/news/#v24-2)
- [Changelog](https://github.com/pypa/pip/blob/24.2/NEWS.rst#242-2024-07-28)
- [Commits](https://github.com/pypa/pip/compare/23.3...24.2)
> chore(deps): Update `pip` from 23.3 to 24.2

- pyproject.toml
- requirements-dev.in
- requirements-dev.txt
- [Software Repository](https://pypi.org/project/wheel/0.44.0/)
- [Release notes](https://github.com/pypa/wheel/releases/tag/0.44.0)
- [Changelog](https://github.com/pypa/wheel/blob/0.44.0/docs/news.rst)
- [Commits](https://github.com/pypa/wheel/compare/0.43.0...0.44.0)
> chore(deps): Update `wheel` from ≤0.43.0 to 0.44.0

- requirements.in
- requirements.txt
- [Software Repository](https://pypi.org/project/pydantic/2.9.2/)
- [Release notes](https://github.com/pydantic/pydantic/releases/tag/v2.9.2)
- [Changelog](https://github.com/pydantic/pydantic/blob/v2.9.2/HISTORY.md#v292-2024-09-17)
- [Commits](https://github.com/pydantic/pydantic/compare/v2.8.2...v2.9.2)
> deps: Update `pydantic` from 2.8.2 to 2.9.2

- .bumpversion.cfg
- HISTORY.md
- src/cl_sii/__init__.py
- (PR #706, 2024-09-26) Improvements and fixes related to validation of trusted inputs
- (PR #582, 2024-09-26) Add configuration for ignoring revisions in Git Blame
- (PR #707, 2024-09-26) Make file `setup.py` executable again
> Release v0.35.0

- requirements-dev.in
- requirements-dev.txt
- [Software Repository](https://pypi.org/project/mypy/1.13.0/)
- [Release notes](https://github.com/python/mypy/releases/tag/v1.13.0)
- [Changelog](https://github.com/python/mypy/blob/v1.13.0/CHANGELOG.md#mypy-113)
- [Commits](https://github.com/python/mypy/compare/v1.11.2...v1.13.0)
> chore(deps): Update `mypy` from 1.11.2 to 1.13.0

- .bumpversion.cfg
- HISTORY.md
- src/cl_sii/__init__.py
- (PR #753, 2025-01-08) Exclude only individual test files in Mypy configuration
- (PR #755, 2025-01-08) Improve Make tasks `clean-build`, `clean-pyc`, and `clean-test`
> Release v0.41.0

- .bumpversion.cfg
- HISTORY.md
- src/cl_sii/__init__.py
- (PR #783, 2025-03-13) deps: Update `packaging` from 24.1 to 24.2
> Release v0.44.0

- pyproject.toml
- Update requirement in `pyproject.toml` file.
Ref: https://app.shortcut.com/cordada/story/13263 [sc-13263]
> Require Python ≥3.9

- .github/workflows/dependency-review.yaml
Ref: Commit b7ea3abdf29b65bc1df2fe75521ee13781c7bcff
Ref: https://github.com/cordada/lib-cl-sii-python/pull/790
> Trigger GitHub Dependency Review when draft pull request is ready for review

- requirements.in
- requirements.txt
- [Software Repository](https://pypi.org/project/signxml/4.0.5/)
- [Release Notes](https://github.com/XML-Security/signxml/releases/tag/v4.0.5)
- [Changelog](https://github.com/XML-Security/signxml/blob/v4.0.5/Changes.rst#changes-for-v405-2025-06-02)
- [Commits](https://github.com/XML-Security/signxml/compare/v4.0.3...v4.0.5)
> deps: Update `signxml` from 4.0.3 to 4.0.5

- .editorconfig-checker.json
Ref: https://app.shortcut.com/cordada/story/15640 [sc-15640]
> chore(task): Update editorconfig checker

- .bumpversion.cfg
- HISTORY.md
- src/cl_sii/__init__.py
- (PR #852, 2025-08-21) rcv: Add RvTipoVenta enum to represent "Tipo de Venta" in RCV
- (PR #853, 2025-08-21) rcv: Extend RcTipoCompra enum with new purchase types
> Release v0.51.0
