cordada/lib-cl-sii-python

.circleci/config.yml

Source:
https://github.com/fyndata/gcp-utils-python/blob/6f594fd/.circleci/config.yml

Config CircleCI

---

cl_sii/extras/dj_model_fields.py
cl_sii/extras/drf_fields.py
cl_sii/extras/mm_fields.py
requirements/base.txt
requirements/extras.txt
setup.cfg
setup.py
tests/test_extras_dj_model_fields.py
tests/test_extras_drf_fields.py
tests/test_extras_mm_fields.py

A separate field class for:
- Django model.
- DRF (Django REST Framework) serializer.
- MM (marshmallow) schema.
Some tests have not been implemented.

extras: add 'RutField' for Django models, DRF and MM

---

MANIFEST.in
cl_sii/data/ref/factura_electronica/schema_dte/DTE_v10.xsd
cl_sii/data/ref/factura_electronica/schema_dte/EnvioDTE_v10.xsd
cl_sii/data/ref/factura_electronica/schema_dte/README.md
cl_sii/data/ref/factura_electronica/schema_dte/SiiTypes_v10.xsd
cl_sii/data/ref/factura_electronica/schema_dte/xmldsignature_v10.xsd
cl_sii/data/ref/factura_electronica/schema_iecv/LceCal_v10.xsd
cl_sii/data/ref/factura_electronica/schema_iecv/LceCoCertif_v10.xsd
cl_sii/data/ref/factura_electronica/schema_iecv/LceSiiTypes_v10.xsd
cl_sii/data/ref/factura_electronica/schema_iecv/LibroCV_v10.xsd
cl_sii/data/ref/factura_electronica/schema_iecv/README.md
cl_sii/data/ref/factura_electronica/schema_iecv/xmldsignature_v10.xsd
setup.py

Official schemas of entities related to these domain concepts:
- DTE (Documento Tributario Electrónico)
- IECV (Información Electrónica de Libros de Compra y Venta)
- LCE (Libros Contables Electrónicos)
Includes a README file per schema set.
All the files have been preserved as they were; schemas are in their original text encoding (ISO-8859-1) and have not been modified in the slightest way.
Include the XML schema (`.xsd`) files in the distribution packages (source and wheel).
Sources (2018-11-28):
http://www.sii.cl/factura_electronica/schema_dte.zip
http://www.sii.cl/factura_electronica/schema_iecv.zip
Update schemas from an unofficial source since the files available on SII's website are outdated with respect to the regulations (and even to the documentation PDFs published alongside). …

data.ref: add XML schemas of "factura electrónica" 

---

cl_sii/contribuyente/constants.py
cl_sii/dte/constants.py
cl_sii/libs/__init__.py
cl_sii/libs/mm_utils.py
cl_sii/libs/tz_utils.py
cl_sii/rcv/__init__.py
cl_sii/rcv/parse.py
requirements/base.txt
setup.cfg
setup.py
tests/test_contribuyente.py
tests/test_dte.py
tests/test_libs_mm_utils.py
tests/test_libs_tz_utils.py
tests/test_rcv.py
tests/test_rcv_parse.py

Useful for dealing with SII RCV ("Registro de Compras y Ventas").
Its main feature is the function `process_rcv_csv_file`.
Test have not been implemented.
For code related to "contribuyente" (tax payer).
Just constants for the moment.
For code related to "dte" (Documento Tributario Electrónico).
Just an enum and constants for the moment.
Utils for dealing with timezone-aware datetime objects.
Test have not been implemented.
Custom marshmallow field `CustomMarshmallowDateField`.
Test have not been implemented.

add sub-package `rcv`

---

cl_sii/libs/xml_utils.py
requirements/base.txt
setup.cfg
setup.py
tests/test_data/xml/attacks/billion-laughs-1.xml
tests/test_data/xml/attacks/billion-laughs-2.xml
tests/test_data/xml/attacks/external-entity-expansion-remote.xml
tests/test_data/xml/attacks/quadratic-blowup-entity-expansion.xml
tests/test_data/xml/trivial.xml
tests/test_xml_utils.py
tests/utils.py

Add helper functions (plus some related exception classes).
- `parse_untrusted_xml`: handles the numerous issues and concerns related to parsing untrusted XML data.
- `read_xml_schema`: instantiate an XML schema object from a file.
- `validate_xml_doc`: validate an XML document against an XML schema.
Some tests have not been implemented.

 libs: add module `xml_utils`

---

cl_sii/dte/data_models.py
tests/test_dte_data_models.py

Include the following 'dataclasses' (and some related validators):
- `DteNaturalKey`
- `DteDataL0`
- `DteDataL1`
- `DteDataL2`
Tests have not been implemented.

dte: add module `data_models`

---

cl_sii/dte/parse.py
tests/test_dte_parse.py

Code for parsing DTE data from representation as XML document (support for other representations may be added later on).
Main function is `parse_dte_xml`, and the helpers are `clean_dte_xml` and `validate_dte_xml`.
Tests have not been implemented.

dte: add module `parse`

---

cl_sii/dte/parse.py
cl_sii/libs/xml_utils.py
scripts/clean_dte_xml_file.py
tests/test_dte_parse.py
tests/test_libs_xml_utils.py
tests/test_scripts_clean_dte_xml_file.py

Augment and improve it to consider more cleaning operations.
**Breaks compatibility**.
Signature changed from
`clean_dte_xml(xml_doc: lxml.etree.ElementBase) -> bool`
to
`clean_dte_xml(xml_doc: lxml.etree.ElementBase, set_missing_xmlns: bool = False,  remove_doc_personalizado: bool = True) -> Tuple[lxml.etree.ElementBase, bool]`
- Add `_set_dte_xml_missing_xmlns`.
- Refactor `_remove_dte_xml_doc_personalizado` out of `clean_dte_xml`.
Tests have not been implemented (just a full "integration test" has).

dte.parse: change and improve `clean_dte_xml`

---

cl_sii/data/ref/factura_electronica/schemas-xml/AEC_v10.xsd
cl_sii/data/ref/factura_electronica/schemas-xml/Cesion_v10.xsd
cl_sii/data/ref/factura_electronica/schemas-xml/DTECedido_v10.xsd
cl_sii/data/ref/factura_electronica/schemas-xml/README.md
cl_sii/data/ref/factura_electronica/schemas-xml/Recibos_v10.xsd

"Formato XML del Archivo Electrónico de Cesión" of the "Registro electrónico de cesión de créditos".
Source (2019-04-16): http://www.sii.cl/factura_electronica/schema_cesion.zip
Some files were ignored:
- `DTE_v10.xsd`: there is a newer version in the repo.
- `SiiTypes_v10.xsd`: there is a newer version in the repo.
- `xmldsignature_v10.xsd`: identical to the version in the repo.
The included files are up to date with respect to those in repository/project ["LibreDTE" (39156263)](https://github.com/LibreDTE/libredte-lib/tree/39156263/schemas)
MD5 checksums:
- `82d426fc3bd5f3a29e61a1d07ed4d6dd  schema_cesion.zip`
- `8e80522d91bcf99077c12e15354eeae4  schema_cesion/AEC_v10.xsd`
- `8db534d686bc84fc7960199dd5fdacd8  schema_cesion/Cesion_v10.xsd`
- `b2fd1907af733ae9401604c694837a85 …

data.ref: add XML schemas for "Cesion" (RTC)

---

cl_sii/libs/xml_utils.py
tests/test_libs_xml_utils.py

- Add class aliases.
- Add `XML_DSIG_NS_MAP` (for XML (Digital) Signature).

libs.xml_utils: misc improvements

---

cl_sii/dte/constants.py
cl_sii/dte/data_models.py
cl_sii/dte/parse.py
tests/test_dte_constants.py
tests/test_dte_data_models.py
tests/test_dte_parse.py

- Add fields to `data_models.DteDataL2`.
- Add properties to `data_models.DteDataL1`.
- Re-implement, improve and augment `parse.parse_dte_xml`.
- Add helper properties to `TipoDteEnum`.
- Implement missing tests for `data_models`.
- Implement missing tests for `constants`.
- Add fields to `DteDataL2`:
- `firma_documento_dt_naive`
- `signature_value_base64`
- `signature_x509_cert_base64`
- `emisor_giro`
- `emisor_email`
- `receptor_email`
- Add properties to `DteDataL1`:
- `vendedor_rut`
- `deudor_rut`
- Remove redundant property `DteDataL1.natural_key`
- Implement missing tests (and add some test stubs).
- Re-implement, improve and augment `parse_dte_xml`.
- Improve tests.
- Fix poor usage of 'lxml'.
- Add helper properties to `TipoDteEnum`.
- Improve docstrings and comments a little.
- …

dte: many improvements

---

requirements/base.txt
requirements/extras.txt
requirements/release.txt
requirements/test.txt
setup.py

Add:
- 'cryptography'
- 'pyOpenSSL'
- 'signxml'
Update:
- 'lxml'
- 'pytz'
- 'djangorestframework' (extras)
- others not too relevant

requirements: add and update packages

---

cl_sii/libs/crypto_utils.py
setup.cfg
tests/test_libs_crypto_utils.py

Among others, it includes functions:
- `load_pem_x509_cert`
- `add_pem_cert_header_footer`
- `remove_pem_cert_header_footer`
Some tests have not been implemented yet.

libs: add module `crypto_utils`

---

docs/project-maintenance.rst

The command `bumpversion --new-version 'X.Y.Z'` doesn't work.
It returns the error `the following arguments are required: part`.
The `part` argument doesn't matter when a complete new version number
is specified, but `bumpversion` still complains if that parameter is
missing.
This change fixes the error by adding a dummy `part` argument.
Ref:
- [Slack](https://fynpal-hq.slack.com/archives/CFGURBDBK/p1557152981014100?thread_ts=1556809374.013500&cid=CFGURBDBK)
- [Slack](https://fynpal-hq.slack.com/archives/CFGURBDBK/p1557154032014300?thread_ts=1556809374.013500&cid=CFGURBDBK)
- [Slack](https://fynpal-hq.slack.com/archives/CFGURBDBK/p1557154124014600?thread_ts=1556809374.013500&cid=CFGURBDBK)

docs: Fix `bumpversion` command

---

cl_sii/libs/tz_utils.py
cl_sii/rcv/parse.py
tests/test_libs_tz_utils.py

- Add aware/naive inspection helpers
- Rename timezone constants (aliases created for compatibility).

libs.tz_utils: minor improvements

---

cl_sii/libs/crypto_utils.py
tests/test_libs_crypto_utils.py

To load an X.509 certificate from DER-encoded certificate data, and convert between DER-encoded and PEM-encoded certificate data.
New functions:
- `load_der_x509_cert`
- `x509_cert_der_to_pem`
- `x509_cert_pem_to_der`

libs.crypto_utils: add functions

---

cl_sii/dte/data_models.py
cl_sii/dte/parse.py
tests/test_dte_data_models.py
tests/test_dte_parse.py

Rename to `firma_documento_dt` and hold the timezone-aware value instead
of "naive".
**Breaks backwards compatibility**.

dte.data_models: alter field `DteDataL2.firma_documento_dt_naive`

---

cl_sii/dte/data_models.py
cl_sii/dte/parse.py
tests/test_dte_data_models.py
tests/test_dte_parse.py

Rename to `signature_x509_cert_der` and hold the X.509 certificate's DER-encoded data instead of PEM-encoded data.
**Breaks backwards compatibility**.

dte.data_models: alter field `DteDataL2.signature_x509_cert_pem`

---

.bumpversion.cfg
HISTORY.rst
cl_sii/__init__.py
cl_sii/dte/parse.py
cl_sii/libs/encoding_utils.py
tests/test_data/sii-dte/DTE--76354771-K--33--170--cleaned-mod-empty-emails.xml
tests/test_dte_parse.py

- (PR #45, 2019-05-15) libs.encoding_utils: improve `clean_base64`
- (PR #44, 2019-05-15) dte.parse: fix edge case in `parse_dte_xml`

Release 0.6.2

---

cl_sii/rcv/parse_csv.py
tests/test_rcv_parse_csv.py

Includes function `parse_rcv_venta_csv_file`.
Tests have not been implemented.

rcv: add module `parse_csv`

---

.bumpversion.cfg
HISTORY.rst
cl_sii/__init__.py
cl_sii/dte/data_models.py
cl_sii/libs/csv_utils.py
cl_sii/libs/mm_utils.py
cl_sii/libs/rows_processing.py
cl_sii/rcv/parse_csv.py
scripts/example.py
tests/test_dte_data_models.py
tests/test_libs_csv_utils.py
tests/test_libs_mm_utils.py
tests/test_libs_rows_processing.py
tests/test_rcv_parse_csv.py

- (PR #52, 2019-05-24) rcv: add module `parse_csv`
- (PR #51, 2019-05-24) libs: add module `rows_processing`
- (PR #50, 2019-05-24) libs: add module `csv_utils`
- (PR #49, 2019-05-24) libs.mm_utils: add `validate_no_unexpected_input_fields`
- (PR #48, 2019-05-24) dte.data_models: add `DteDataL2.as_dte_data_l1`

Release v0.6.3

---

.bumpversion.cfg
.circleci/config.yml
HISTORY.rst
cl_sii/__init__.py
cl_sii/libs/dataclass_utils.py
cl_sii/libs/xml_utils.py
requirements/release.txt
requirements/test.txt
tests/test_data/xml/trivial-doc.xml
tests/test_libs_dataclass_utils.py
tests/test_libs_xml_utils.py
tox.ini

- (PR #55, 2019-05-29) libs.xml_utils: add `verify_xml_signature`
- (PR #54, 2019-05-28) libs: add module `dataclass_utils`

Release v0.6.4

---

cl_sii/libs/xml_utils.py
tests/test_libs_xml_utils.py

- Do not log a misleading error message.
- Fix docstring.
- Also add tests to cover related cases.

libs.xml_utils: minor fix to `verify_xml_signature`

---

cl_sii/dte/data_models.py
cl_sii/libs/tz_utils.py
tests/test_dte_data_models.py
tests/test_libs_tz_utils.py

- Add function `validate_dt_tz`
- Add function `convert_tz_aware_dt_to_naive`.
- Remove `TZ_CL_SANTIAGO` (reference it from `base.constants` instead).

libs.tz_utils: misc

---

cl_sii/extras/mm_fields.py
cl_sii/rcv/__init__.py
cl_sii/rcv/constants.py
cl_sii/rcv/data_models.py
tests/test_extras_mm_fields.py
tests/test_rcv_constants.py

- Add module `rcv.data_models`.
- Add module `rcv.constants`.
- Add marshmallow field `RcvTipoDoctoField` (for RCV's "tipo documento").

rcv: add data models, constants and more

---

cl_sii/libs/io_utils.py
tests/test_libs_io_utils.py

Include functions:
- `with_mode_binary`
- `with_mode_text`
- `with_encoding_utf8`

libs: add module `io_utils`

---

cl_sii/rcv/parse_csv.py

- Now they yield dataclass `RcvDetalleEntry` instances instead of dataclass `DteDataL2` instances.
- Params `{emisor, receptor}_{rut, razon_social}` renamed to `rut` and `razon_social` respectively.
- `parse_rcv_venta_csv_file`: fields `Fecha Acuse Recibo` and `Fecha Reclamo` are not ignored anymore.
- Marshmallow schemas' field `tipo_dte` replaced by `tipo_docto`.
- Marshmallow schemas' method `to_dte_data_l2` replaced by `to_detalle_entry`.

rcv.parse_csv: significant changes to parse functions

---

cl_sii/rcv/parse_csv.py
tests/test_rcv_parse_csv.py

In parse functions (`parse_rcv_X_csv_file`).
Fixes #65.

rcv.parse_csv: detect invalid value of "razon social"

---

cl_sii/libs/tz_utils.py
cl_sii/rcv/data_models.py

Python datetime objects require special care when setting their time zone information. Under certain conditions, `datetime.datetime.replace(tzinfo=TZ)` and `datetime.datetime(tzinfo=TZ)` may produce incorrect results.

libs.tz_utils: Fix setting of time zone information in datetimes

---

cl_sii/rut/__init__.py
tests/test_rut.py

Example: `Rut('01234567-4')` becomes `Rut('1234567-4')`

rut: Strip leading zeros from RUTs

---

cl_sii/rut/__init__.py
tests/test_rut.py

Implement the following "rich comparison" (magic) methods that were missing:
- `object.__lt__(self, other)`
- `object.__le__(self, other)`
Ref: https://docs.python.org/3/reference/datamodel.html#object.__ge__

rut: Add less-than and greater-than methods

---

cl_sii/extras/dj_model_fields.py
tests/test_extras_dj_model_fields.py

The method `cl_sii.extras.dj_model_fields.RutField.get_prep_value(value)`
expects a `Rut`-typed R.U.T. `value`, which usually is fine.
However, when executing a query, it may be sometimes desirable to pass the
R.U.T. value as a string rather than as an instance of the `Rut` class.
For example, when using the Django Shell, it is more convenient to type
`ExampleModel.objects.get(rut='60803000-K')` than
`ExampleModel.objects.get(rut=Rut('60803000-K'))`, because the former avoids
needing to import the `Rut` class and is quicker to type. The same thing goes
for instances of the `uuid.UUID` class.
Before this commit, the `str`-typed R.U.T. would raise an `AttributeError`,
because `django.db.models.lookups.Lookup.get_prep_lookup()` passes the string to
`RutField.get_prep_value(value)` without …

extras: Handle `str`-typed RUTs in `Django RutField.get_prep_value()`

---

.bumpversion.cfg
HISTORY.rst
cl_sii/__init__.py
cl_sii/extras/dj_model_fields.py
cl_sii/libs/tz_utils.py
cl_sii/rcv/data_models.py
cl_sii/rut/__init__.py
requirements/release.txt
requirements/test.txt
scripts/clean_dte_xml_file.py
tests/test_extras_dj_model_fields.py
tests/test_libs_xml_utils.py
tests/test_rut.py

- (PR #72, 2019-07-08) extras: Handle `str`-typed RUTs in `Django RutField.get_prep_value()`
- (PR #70, 2019-07-05) rut: Add less-than and greater-than methods
- (PR #71, 2019-07-05) rut: Strip leading zeros from RUTs
- (PR #69, 2019-07-02) libs.tz_utils: Fix setting of time zone information in datetimes
- (PR #68, 2019-06-27) requirements: update all those for 'release' and 'test'

Release v0.7.2

---

requirements/base.txt
setup.py

Either the version used for development (and official support), the one required, or both.
Packages:
- `lxml`
- `marshmallow`
- `pytz`
- `django` (extras)
- `djangorestframework` (extras)

requirements: update main packages

---

cl_sii/cte/f29/parse_datos_obj.py

- Add parameters for the validator and the deserializer to `cl_sii.cte.f29.parse_datos_obj`.
- Add new "best-effort" deserializer that can be used when it's OK to ignore errors.

cte: Add custom validators and deserializers to parser

---

cl_sii/libs/csv_utils.py
requirements/base.txt
requirements/release.txt
requirements/test.txt
tests/test_libs_crypto_utils.py

Significant packages that were updated:
- `cryptography`: required some changes to test code
- `jsonschema`
- `mypy`: required minimal code changes
Packages no longer needed: no.
Similar to https://github.com/fyntex/lib-cl-sii-api-python/pull/134

requirements: several updates

---

cl_sii/dte/data_models.py
cl_sii/dte/parse.py
tests/test_dte_data_models.py
tests/test_dte_parse.py

Add data model `DteXmlData`, which is exactly the same (regarding fields) as `DteDataL2`.
The ultimate goal is having separate models with different fields. This is the first step of making that possible without breaking other project's code.
Function `parse_dte_xml` return type is now `DteXmlData` instead of `DteDataL2`.

dte.data_models: add 'DteXmlData'

---

cl_sii/rcv/parse_csv.py

Function `get_rcv_csv_file_parser` and its related type `RcvCsvFileParserType`.
Source: https://github.com/fyntex/fd-cl-data/blob/ab4469402c8e4d50656f443eb93c900127f27bdd/fd_cl_data/apps/sii_rcv/models.py#L899-L952

rcv.parse_csv: move code from 'fd-cl-data' in here

---

cl_sii/rcv/data_models.py

Move fields `emisor_razon_social` and `receptor_razon_social` of `RcvDetalleEntry` to its subclasses, where they will be modified later.

rcv.data_models: move some fields to subclasses

---

.bumpversion.cfg
cl_sii/__init__.py
cl_sii/dte/data_models.py
cl_sii/dte/parse.py
cl_sii/libs/csv_utils.py
cl_sii/rcv/data_models.py
cl_sii/rcv/parse_csv.py
requirements/base.txt
requirements/release.txt
requirements/test.txt
tests/test_dte_data_models.py
tests/test_dte_parse.py
tests/test_libs_crypto_utils.py

- (PR #110, 2020-04-13) rcv.data_models: move some fields to subclasses
- (PR #109, 2020-04-13) rcv.parse_csv: move code from 'fd-cl-data' in here
- (PR #108, 2020-04-13) dte.data_models: add 'DteXmlData'
- (PR #107, 2020-04-10) requirements: several updates

Release v0.10.0.a1

---

cl_sii/dte/data_models.py
cl_sii/rcv/data_models.py
tests/test_dte_data_models.py

- `dte.data_models.DteDataL2`: make fields `emisor_razon_social` and `receptor_razon_social` optional.
- `rcv.data_models`: make unnecessary fields optional, which will be removed later on.

data_models: make some fields optional

---

cl_sii/rcv/parse_csv.py
tests/test_rcv_parse_csv.py

Remove param `razon_social` from all `parse_rcv_*_csv_file` functions, and their return type `RcvCsvFileParserType`.
- `parse_rcv_venta_csv_file`
- `parse_rcv_compra_registro_csv_file`
- `parse_rcv_compra_no_incluir_csv_file`
- `parse_rcv_compra_reclamado_csv_file`
- `parse_rcv_compra_pendiente_csv_file`

rcv.parse_csv: remove param `razon_social` from parse functions

---

.bumpversion.cfg
cl_sii/__init__.py
cl_sii/rcv/parse_csv.py
tests/test_rcv_parse_csv.py

- (PR #114, 2020-04-14) rcv.parse_csv: remove param `razon_social` from parse functions

Release v0.10.0.a3

---

cl_sii/rcv/data_models.py
cl_sii/rcv/parse_csv.py

For subclasses of `RcvDetalleEntry` only one of these fields is necessary, which depends on the specific class.
- `emisor_razon_social`
- `receptor_razon_social`
These fields had been made optional in #112 (commit 1f21463).

rcv.data_models: remove unnecessary fields

---

.bumpversion.cfg
HISTORY.rst
cl_sii/__init__.py
cl_sii/rcv/data_models.py
cl_sii/rcv/parse_csv.py
setup.cfg

- (PR #116, 2020-04-14) rcv.data_models: remove unnecessary fields
- (PR #114, 2020-04-14) rcv.parse_csv: remove param `razon_social` from parse functions
- (PR #112, 2020-04-14) data_models: make some fields optional
- (PR #110, 2020-04-13) rcv.data_models: move some fields to subclasses
- (PR #109, 2020-04-13) rcv.parse_csv: move code from 'fd-cl-data' in here
- (PR #108, 2020-04-13) dte.data_models: add 'DteXmlData'
- (PR #107, 2020-04-10) requirements: several updates

Release v0.10.0

---

.circleci/config.yml

We need to use `pip check` because it returns a non-zero exit status
when there are dependency version conflicts. `pip install` just prints a
warning, which does not cause a CI failure.
See also: https://github.com/pypa/pip/issues/6200

config: Verify Python dependency compatibility in CI

---

cl_sii/rtc/__init__.py

For SII's "RTC/RPETC".
Concepts and acronyms used interchangeably:
- "Registro Transferencia de Crédito" (RTC)
- "Registro Público Electrónico de Transferencia de Crédito" (RPETC)
- "Registro Electrónico de Cesión de Créditos"
The commit was taken from https://github.com/fyntex/lib-cl-sii-api-python/commit/50470e85c7eca1dc7f9f3abc4623e26f77f87615.

Add sub-package `rtc`

---

cl_sii/rtc/constants.py
tests/test_rtc_constants.py

- Add `RolContribuyenteEnCesion`.
- Add `TIPO_DTE_CEDIBLES`.
These commits were taken from:
- https://github.com/fyntex/lib-cl-sii-api-python/commit/0bafb09711cfe1695e27f82eeeb8686b8f8626d3
- https://github.com/fyntex/lib-cl-sii-api-python/commit/8a4fef80ca0ee397d7d72f28a1580832629266d0
Ref: https://github.com/fyntex/lib-cl-sii-api-python/issues/162

rtc: Add constants

---

.circleci/config.yml

CI workflows will finish faster if we do not attempt to build distributable artifacts when tests fail.

config: Make CI 'dist' job depend on 'test' jobs

---

requirements/base.txt

(plus its dependency `future`)
Changelog:
- 1.0.0 (2019-12-01)
https://github.com/kislyuk/eight/blob/v1.0.0/Changes.rst#changes-for-v100-2019-12-01
Code diff: https://github.com/kislyuk/eight/compare/v0.4.2...v1.0.0
Replaces: https://github.com/fyntex/lib-cl-sii-python/pull/143.

requirements: update 'eight' (dependency of 'signxml')

---

requirements/base.txt

Changelog:
- 2.8.1 (2020-10-29):
https://github.com/XML-Security/signxml/blob/v2.8.1/Changes.rst#changes-for-v281-2020-10-29
Code diff: https://github.com/XML-Security/signxml/compare/v2.8.0...v2.8.1

requirements: Update 'signxml'

---

requirements/base.txt
tests/test_libs_crypto_utils.py

Changelog:
- 3.3.1 (2020-12-09):
https://github.com/pyca/cryptography/blob/3.3.1/CHANGELOG.rst#331---2020-12-09
- 3.3 (2020-12-08):
https://github.com/pyca/cryptography/blob/3.3.1/CHANGELOG.rst#33---2020-12-08
- 3.2.1 (2020-10-27):
https://github.com/pyca/cryptography/blob/3.3.1/CHANGELOG.rst#321---2020-10-27
Code diff: https://github.com/pyca/cryptography/compare/3.2...3.3.1
-----
- Fix test.
- Fix incorrect commit 493285a146a0e925a73996b8a493a2e15eee8551 (for an explanation, see https://github.com/fyntex/lib-cl-sii-python/pull/160#issuecomment-745709570).

requirements: Update 'cryptography'

---

requirements/base.txt
setup.cfg
setup.py

"Data validation and settings management using python type annotations."
"pydantic enforces type hints at runtime, and provides user friendly
errors when data is invalid."
- https://pydantic-docs.helpmanual.io
- https://github.com/samuelcolvin/pydantic
-----
This library will be used in future pull requests.

requirements: Add 'pydantic'

---

cl_sii/libs/tz_utils.py
tests/test_libs_tz_utils.py

The `zone` attribute is not defined in the abstract base class
`datetime.tzinfo`. We need to check that it is there before using it in
the function `validate_dt_tz` to prevent unexpected exceptions when
dealing with Python Standard Library time zones that are instances of
class `datetime.timezone`.

libs.tz_utils: Add checks to validate_dt_tz

---

cl_sii/rtc/constants.py
cl_sii/rtc/data_models.py
cl_sii/rtc/data_models_cesiones_periodo.py
tests/test_rtc_data_models.py

- constants: Add 'monto cedido' and 'sequence number'.
- data_models: Add "cesión" natural key and alternative natural key.
- data_models_cesiones_periodo: Replace hardcoded values with constants.

rtc: Add constants and "cesión" natural keys

---

.bumpversion.cfg
HISTORY.rst
cl_sii/__init__.py
cl_sii/libs/tz_utils.py
cl_sii/rtc/constants.py
cl_sii/rtc/data_models.py
cl_sii/rtc/data_models_cesiones_periodo.py
requirements/base.txt
requirements/test.txt
setup.cfg
setup.py
tests/test_libs_crypto_utils.py
tests/test_libs_tz_utils.py
tests/test_rtc_data_models.py
tests/test_rtc_data_models_cesiones_periodo.py

- (PR #166, 2020-12-15) requirements: Update 'cryptography'
- (PR #169, 2020-12-16) build(deps): bump coverage from 4.5.3 to 5.3
- (PR #172, 2020-12-22) rtc: Add data model for "Cesiones Periodo" entries
- (PR #173, 2021-01-05) requirements: Add 'pydantic'
- (PR #175, 2021-01-06) libs.tz_utils: Add checks to validate_dt_tz
- (PR #174, 2021-01-07) rtc: Add constants and "cesión" natural keys
- (PR #171, 2021-01-07) build(deps): bump codecov from 2.1.9 to 2.1.11

Release v0.11.2

---

cl_sii/rtc/data_models_aec.py
cl_sii/rtc/parse_aec.py
tests/test_rtc_data_models_aec.py
tests/test_rtc_parse_aec.py

- Add data model for the SII's "Archivo Electrónico de Cesión" (AEC) in XML format.
- Add data model for the "cesiones" contained in an AEC.
- Add parser for AECs in XML format.
- Add tests.

rtc: Add data models and parser for AECs

---

cl_sii/rtc/data_models.py
cl_sii/rtc/data_models_aec.py
tests/test_rtc_data_models.py
tests/test_rtc_data_models_aec.py

- data_models: Add method to create `CesionL1` from `CesionL2`.
- data_models: Add method to create `CesionL0` from `CesionL1`.
- data_models_aec: Add method to create `CesionL2` from `CesionAecXml`.

rtc: Add methods to build CesionL2, CesionL1, and CesionL0 from other data models

---

.bumpversion.cfg
HISTORY.rst
cl_sii/__init__.py
cl_sii/rtc/data_models.py
cl_sii/rtc/data_models_aec.py
tests/test_rtc_data_models.py
tests/test_rtc_data_models_aec.py

- (PR #186, 2021-02-09) rtc: Add methods to build CesionL2, CesionL1, and CesionL0 from other data models

Release v0.12.1

---

.bumpversion.cfg
HISTORY.rst
cl_sii/__init__.py
requirements/base.txt
requirements/release.txt
requirements/test.txt

- (PR #177, 2021-02-16) build(deps): bump lxml from 4.5.0 to 4.6.2
- (PR #188, 2021-02-16) build(deps): bump cryptography from 3.3.1 to 3.3.2
- (PR #176, 2021-02-16) build(deps): bump zipp from 3.1.0 to 3.4.0
- (PR #167, 2021-02-16) build(deps): bump py from 1.8.1 to 1.10.0
- (PR #189, 2021-02-16) build(deps): bump certifi from 2020.4.5.1 to 2020.12.5
- (PR #185, 2021-02-16) build(deps): bump pkginfo from 1.5.0.1 to 1.7.0
- (PR #191, 2021-02-16) build(deps): bump pyrsistent from 0.16.0 to 0.17.3
- (PR #190, 2021-02-16) build(deps): bump typed-ast from 1.4.1 to 1.4.2

Release v0.12.2

---

cl_sii/extras/dj_form_fields.py
tests/test_extras_dj_form_fields.py

A separate field class for Django form
Previous: https://github.com/fyntex/lib-cl-sii-python/pull/5

extras: add 'RutField' for Django forms

---

.bumpversion.cfg
HISTORY.rst
cl_sii/__init__.py
cl_sii/extras/dj_form_fields.py
requirements/base.txt
tests/test_extras_dj_form_fields.py

- (PR #193, 2021-02-16) requirements: Update dependency graph of base requirements
- (PR #197, 2021-02-26) extras: add 'RutField' for Django forms

Release v0.12.3

---

cl_sii/rtc/data_models_aec.py
tests/test_rtc_data_models_aec.py

The coincidence between the fields `fecha_firma_dt` and `fecha_cesion_dt` in a 'cesion' is not mentioned among the validations that the SII performs to accept an AEC XML Document, in fact, there are known cases of valid AEC XML Documents where these fields do not have the same date, with a slight difference of a few seconds, but still, the AEC is valid for the SII.
Ref. [Instructivo Técnico Registro Público Electrónico de Transferencia de Crédito](https://github.com/cl-sii-extraoficial/archivos-oficiales/blob/master/src/docs/rtc/README.md#instructivo-t%C3%A9cnico)
ref https://github.com/fyntex/fd-cl-data/issues/671

rtc.data_models_aec: remove match validation for 'fecha_firma_dt' and 'fecha_cesion_dt'

---

cl_sii/rtc/data_models_aec.py
tests/test_rtc_data_models_aec.py

Although the validation of the progression of the value 'monto_cesion' through the 'cesiones' in an AECXml seems to make a lot of sense, there are known SII-approved AECs where the 'monto_cesion' of a 'cesion' exceeds the value of its predecessor.
This validation is not documented among those carried out by the SII at the time of uploading an AEC
Ref. Instructivo Técnico Registro Público Electrónico de Transferencia de Crédito
Source: (https://github.com/cl-sii-extraoficial/archivos-oficiales/blob/master/src/docs/rtc/README.md#instructivo-t%C3%A9cnico)

rtc.data_models_aec: remove validation for the progression of 'monto_cesion' across the 'cesiones'

---

.bumpversion.cfg
.circleci/config.yml
HISTORY.rst
cl_sii/__init__.py
cl_sii/rtc/data_models_aec.py
requirements/base.txt
requirements/extras.txt
requirements/release.txt
requirements/test.txt
setup.py
tests/test_rtc_data_models_aec.py

-  (PR #195, 2021-04-15) build(deps): bump requests from 2.23.0 to 2.25.1
-  (PR #212, 2021-04-14) config: Update Python version used in CI jobs to 3.8.9
- (PR #210, 2021-04-13) rtc.data_models_aec: remove validation for the progression of 'monto_cesion' across the 'cesiones'
- (PR #207, 2021-04-08) build(deps): bump virtualenv from 20.0.31 to 20.4.3
- (PR #208, 2021-04-08) rtc.data_models_aec: remove match validation for 'fecha_firma_dt' and 'fecha_cesion_dt'
- (PR #205, 2021-03-26) build(deps): bump lxml from 4.6.2 to 4.6.3
- (PR #204, 2021-03-24) requirements: Upgrade 'Django'

Release v0.12.4

---

docs/project-maintenance.rst

The GitHub pull request for the new release uses `develop` as the head branch. Before the pull request is merged, additional commits may be pushed to `develop`, and those commits will be merged into the base branch when the pull request is finally merged, even though what we wanted to merge was not actually `develop`, but the tag of the new version.
The documentation is updated with a workaround that "freezes" `develop` by creating a branch that points to the tag of the new version, so that the new branch is used as head branch instead of `develop`.
Ref: https://github.com/fyntex/lib-cl-sii-api-python/pull/236.

docs: Add creation of release branch to instructions for new releases

---

requirements/base.txt
setup.py

Upgrade Pydantic 1.6.1 -> 1.6.2 with fix for vulnerability:
- https://github.com/samuelcolvin/pydantic/security/advisories/GHSA-5jqp-qgf6-3pvh
Changelog:
- 1.6.2 (2021-05-11):
https://github.com/samuelcolvin/pydantic/blob/v1.6.2/HISTORY.md#v162-2021-05-11
Code diff: https://github.com/samuelcolvin/pydantic/compare/v1.6.1...v1.6.2
Resolves #220

requirements: Upgrade Pydantic

---

.bumpversion.cfg
HISTORY.rst
cl_sii/__init__.py
docs/project-maintenance.rst
requirements/base.txt
requirements/extras.txt
requirements/test.txt
setup.py

- (PR #213, 2021-04-21) build(deps): bump toml from 0.10.1 to 0.10.2
- (PR #216, 2021-04-22) docs: Add creation of release branch to instructions for new releases
- (PR #221, 2021-05-14) requirements: Upgrade Pydantic
- (PR #223, 2021-06-08) requirements: Upgrade 'Django'
- (PR #224, 2021-06-15) requirements: Upgrade 'Django'
- (PR #226, 2021-06-15) requirements: Remove Django upper bound constraint

Release v0.12.5

---

.circleci/config.yml

Changelog:
- 3.8.10 (2021-05-03):
https://docs.python.org/release/3.8.10/whatsnew/changelog.html#python-3-8-10-final

config: Update Python version used in CI jobs to 3.8.10

---

cl_sii/dte/data_models.py
tests/test_dte_data_models.py

- Remove uses of `dataclasses.field` (see comment https://github.com/fyntex/lib-cl-sii-python/pull/218/commits/b7b9854e8de7455f6cc0649ad7b0014a7c948e17#r627092839 by @jtrobles-cdd )
- Refactor validations performed in `__post_init__` as Pydantic validators
- Update tests
Resolves: #229
Ref: https://cordada.aha.io/features/COMPCLDATA-1

dte: Convert stdlib dataclass `DteXmlData` into pydantic dataclass

---

cl_sii/dte/data_models.py
tests/test_dte_data_models.py

- Remove uses of `dataclasses.field` (see comment https://github.com/fyntex/lib-cl-sii-python/pull/218/commits/b7b9854e8de7455f6cc0649ad7b0014a7c948e17#r627092839 by @jtrobles-cdd )
- Refactor validations performed in `__post_init__` as Pydantic validators
- Update tests
Resolves: #232
Ref: #230
Ref: https://cordada.aha.io/features/COMPCLDATA-2

dte: Convert stdlib dataclasses into pydantic dataclasses

---

tests/test_dte_data_models.py

Restores mistakenly deleted regression tests in previous changes when the DteXmlData model was migrated to Pydantic
ref: https://github.com/fyntex/lib-cl-sii-python/pull/230
ref: https://github.com/fyntex/lib-cl-sii-python/pull/40
Thanks to @jtrobles-cdd for pointing out the error in https://github.com/fyntex/lib-cl-sii-python/pull/234#discussion_r685426432

DteXmlData: Restore mistakenly deleted regression tests

---

cl_sii/rut/__init__.py
tests/test_rut.py

`0-0` is a syntactically valid RUT, but it is ignored because every time the `Rut.clean` method is executed, all the leading zeros are removed indiscriminately. These changes adjust the `Rut.clean` method to removes leading zeros except if zero is the only digit, so we can accept the RUT '0-0'.
Ref: https://cordada.aha.io/features/PLATCORE-232

rut: Fix RUT clean method to accept '0-0' value

---

cl_sii/rtc/data_models_aec.py
cl_sii/rtc/parse_aec.py

- There is a contradiction regarding the element `Nombre de la persona autorizada` about what the technical documentation states and how it was implemented in the XML schema. Although the former defines the field as required, the XML schema does not set a minimum required length, so the field can be empty.
- Add validator to parser `.parse_aec._RutAutorizado` that converts empty strings in its `nombre` attribute to `None`.
- Make field `.parse_aec._RutAutorizado.nombre` optional.
- Make field `.data_models_aec.CesionAecXml.cedente_persona_autorizada_nombre` optional.
- Add reusable Pydantic validator that converts empty strings to `None`.
Ref: [FORMATO ARCHIVO ELECTRÓNICO DE CESIÓN](https://github.com/cl-sii-extraoficial/archivos-oficiales/blob/99b15aff252836e1ac311d243636aa3a9e6b89c6/src/ …

rtc: Make AEC field 'nombre persona autorizada cedente' optional

---

setup.py

Require the lxml version 4.6.5 or later to avoid vulnerability GHSA-55x5-fj6c-h6m8
Vulnerability: https://github.com/lxml/lxml/security/advisories/GHSA-55x5-fj6c-h6m8
Vulnerable versions: < 4.6.5
Ref: https://github.com/fyntex/lib-cl-sii-python/pull/255

chore: Increase lxml lower bound constraint

---

.bumpversion.cfg
HISTORY.rst
cl_sii/__init__.py
requirements/base.txt
setup.py

- (PR #258, 2021-12-22) chore: Increase lxml lower bound constraint
- (PR #259, 2021-12-23) requirements: Update 'signxml'

Release v0.15.2

---

cl_sii/rtc/parse_aec.py

There is a high number of AEC documents approved by the SII that cannot be instantiated because the validation that the AEC signature certificate is loadable fails (see https://github.com/fyntex/lib-cl-sii-python/pull/242#issuecomment-932675576). For the moment we will disable this validation so we can instantiate the AEC documents while we look for a solution to the issue loading the AEC signature certificate.
Ref: https://cordada.aha.io/features/COMPCLDATA-13

chore(rtc.parse): Disable validation that AEC signature cert is loadable

---

cl_sii/dte/constants.py
cl_sii/dte/data_models.py
cl_sii/dte/parse.py
cl_sii/extras/mm_fields.py
cl_sii/rcv/constants.py
cl_sii/rtc/constants.py
cl_sii/rtc/data_models.py
cl_sii/rtc/data_models_cesiones_periodo.py
cl_sii/rtc/parse_aec.py
tests/test_dte_constants.py
tests/test_dte_data_models.py
tests/test_dte_parse.py
tests/test_extras_mm_fields.py
tests/test_rcv_constants.py
tests/test_rtc_data_models.py
tests/test_rtc_data_models_aec.py
tests/test_rtc_data_models_cesiones_periodo.py
tests/test_rtc_parse_aec.py

⚠️ **Warning**, this is a breaking change!
- Rename :class:`TipoDteEnum` to :class:`TipoDte` in source code.
- Adapt tests to changes.
Ref: https://cordada.aha.io/features/PLATCORE-309
Ref: https://cordada.aha.io/requirements/PLATCORE-309-1
Closes: https://github.com/fyntex/lib-cl-sii-python/issues/82

Rename of the enum class for `TipoDte` object

---

.bumpversion.cfg
HISTORY.rst
cl_sii/__init__.py
cl_sii/dte/constants.py
cl_sii/dte/data_models.py
cl_sii/dte/parse.py
cl_sii/extras/mm_fields.py
cl_sii/rcv/constants.py
cl_sii/rtc/constants.py
cl_sii/rtc/data_models.py
cl_sii/rtc/data_models_cesiones_periodo.py
cl_sii/rtc/parse_aec.py
tests/test_dte_constants.py
tests/test_dte_data_models.py
tests/test_dte_parse.py
tests/test_extras_mm_fields.py
tests/test_rcv_constants.py
tests/test_rtc_data_models.py
tests/test_rtc_data_models_aec.py
tests/test_rtc_data_models_cesiones_periodo.py
tests/test_rtc_parse_aec.py

- (PR #261, 2021-12-24) chore(rtc.parse): Disable validation that AEC signature cert is loadable
- (PR #253, 2021-12-24) Rename of the enum class for `TipoDte` object

Release v0.16.0

---

cl_sii/rtc/xml_utils.py
tests/test_rtc_xml_utils.py

Add a new method to `cl_sii.rtc.xml_utils` to verify the signature of an AEC XML document using the AEC's digital signature's DER-encoded X.509 certificate.

rtc.xml_utils: Add method to verify signature of AEC XML document

---

.bumpversion.cfg
HISTORY.rst
cl_sii/__init__.py
cl_sii/rtc/xml_utils.py
tests/test_rtc_xml_utils.py

- (PR #264, 2022-01-13) rtc.xml_utils: Add method to verify signature of AEC XML document

Release v0.16.1

---

cl_sii/rcv/data_models.py
tests/test_rcv_data_models.py

- Remove uses of `dataclasses.field` (see comment https://github.com/fyntex/lib-cl-sii-python/pull/218/commits/b7b9854e8de7455f6cc0649ad7b0014a7c948e17#r627092839 by @jtrobles-cdd )
- Refactor validations performed in `__post_init__` as Pydantic validators
- Add tests
Resolves: #235
Ref: https://cordada.aha.io/features/COMPCLDATA-4

rcv: Convert stdlib dataclasses into pydantic dataclasses

---

cl_sii/rut/constants.py
cl_sii/rut/crypto_utils.py
tests/test_libs_crypto_utils.py
tests/test_rut_crypto_utils.py

Get the Chilean RUT stored in a digital certificate.
- Add constant `SII_CERT_TITULAR_RUT_OID`
- Add module `cl_sii.rut.crypto_utils` including the method  `get_subject_rut_from_certificate_pfx`
- Add test

cl_sii.rut: Add method to get the RUT of the certificate holder

---

.github/dependabot.yml

We have multiple open pull requests that were created by Dependabot that have not been merged for various reasons, which prevents Dependabot from creating pull requests for other dependencies that may be of higher priority.

chore: Increase Dependabot's open pull request limit for `pip`

---

requirements/extras.txt
setup.py

Increase limit to 3.14 as the latest release is at version 3.13.1.
Changelog:
- 3.13.1 (2021-12-15):
https://www.django-rest-framework.org/community/release-notes/#3131
- 3.13.0 (2021-12-13):
https://www.django-rest-framework.org/community/release-notes/#3130
Code diff: https://github.com/encode/django-rest-framework/compare/3.12.4...3.13.1
Fixes: https://github.com/fyntex/lib-cl-sii-python/issues/270

chore: Increase Django REST Framework required maximum version to 3.13.x

---

cl_sii/rut/crypto_utils.py
tests/test_rut_crypto_utils.py

When searching for the rut information in the certificate, some
objects inside it could not have the `type_id` attribute. For this
reason, it is necessary to check if this attribute exist before
accessing it.
Ref: https://cordada.aha.io/requirements/COMPCLDATA-67-1
Ref: https://cordada.aha.io/features/COMPCLDATA-67
Fixes: https://github.com/fyntex/lib-cl-sii-python/issues/307

fix(rut): `AttributeError` for `GeneralName` object without `type_id`

---

.bumpversion.cfg
HISTORY.rst
cl_sii/__init__.py
cl_sii/rut/crypto_utils.py
tests/test_rut_crypto_utils.py

- (PR #309, 2022-03-31) fix(rut): `AttributeError` for `GeneralName` object without `type_id`

Release v0.17.2

---

.circleci/config.yml

- Update CI configuration.
Changelog:
- 3.8.13 (2022-03-15):
https://docs.python.org/release/3.8.13/whatsnew/changelog.html#python-3-8-13-final
Ref: https://cordada.aha.io/features/COMPCLDATA-84
Depends on: https://github.com/fyntex/lib-cl-sii-python/pull/326

chore: Update Python to version 3.8.13

---

requirements.txt
tests/test_extras_mm_fields.py

Bumps [marshmallow](https://github.com/marshmallow-code/marshmallow)
- [Release notes](https://github.com/marshmallow-code/marshmallow/releases)
- [Changelog](https://github.com/marshmallow-code/marshmallow/blob/dev/CHANGELOG.rst)
- [Commits](https://github.com/marshmallow-code/marshmallow/compare/2.19.5...2.21.0)
---
updated-dependencies:
- dependency-name: marshmallow
- dependency-type: direct:production
- update-type: version-update: semver-minor
...
Signed-off-by: Samuel [svillegas] <svillegas@cordada.com>
Ref: https://cordada.aha.io/features/COMPCLDATA-115

chore(deps): bump marshmallow from 2.19.5 to 2.21.0

---

.bumpversion.cfg
.circleci/config.yml
.github/dependabot.yml
.github/workflows/git-commit-lint.yaml
CODEOWNERS
HISTORY.rst
Makefile
README.rst
cl_sii/__init__.py
cl_sii/rut/crypto_utils.py
commitlint.config.js
docs/project-maintenance.rst
requirements-dev.txt
requirements.txt
setup.py
tests/test_extras_mm_fields.py
tests/test_libs_crypto_utils.py
tests/test_libs_xml_utils.py

- (PR #343, 2022-07-08) chore: Update Dependabot configuration
- (PR #281, 2022-07-21) build(deps): bump six from 1.15.0 to 1.16.0
- (PR #340, 2022-07-21) build(deps): bump lxml from 4.6.5 to 4.9.1
- (PR #334, 2022-07-22) build(deps): bump certifi from 2020.12.5 to 2022.6.15
- (PR #350, 2022-08-11) chore: Add code owners
- (PR #352, 2022-08-18) chore: Change Dependabot schedule interval from `weekly` to `monthly`
- (PR #338, 2022-08-22) build(deps-dev): bump tox from 3.20.1 to 3.25.1
- (PR #342, 2022-08-22) chore(deps): Bump cryptography from 3.3.2 to 37.0.4
- (PR #286, 2022-08-24) build(deps): bump eight from 1.0.0 to 1.0.1
- (PR #355, 2022-08-24) chore: Add Make tasks for installation
- (PR #332, 2022-08-24) build(deps-dev): bump pkginfo from 1.7.0 to 1.8.3
- (PR #288, 2022-08-24) …

Release v0.18.0

---

requirements.txt
setup.py

Changelog:
- 1.10.1 (2022-08-31):
https://github.com/pydantic/pydantic/blob/v1.10.1/HISTORY.md#v1101-2022-08-31
- 1.10.0 (2022-08-30):
https://github.com/pydantic/pydantic/blob/v1.10.0/HISTORY.md#v1100-2022-08-30
- …
- 1.9.0 (2021-12-31):
https://github.com/pydantic/pydantic/blob/v1.10.0/HISTORY.md#v190-2021-12-31
- 1.8.2 (2021-05-11):
https://pydantic-docs.helpmanual.io/changelog/#v182-2021-05-11
- 1.8.1 (2021-03-03):
https://pydantic-docs.helpmanual.io/changelog/#v181-2021-03-03
- 1.8 (2021-02-26):
https://pydantic-docs.helpmanual.io/changelog/#v18-2021-02-26
- …
- 1.7 (2020-10-26):
https://pydantic-docs.helpmanual.io/changelog/#v17-2020-10-26
Code diff: https://github.com/pydantic/pydantic/compare/v1.6.2...v1.10.1
---
Add version exclusions for Pydantic 1.7.*, 1.8.*, and 1.9.* to …

chore(deps): Update 'pydantic' from version 1.6.2 to 1.10.1

---

requirements-dev.txt
requirements.in
requirements.txt

Ref: https://cordada.aha.io/features/COMPCLDATA-130

fix(deps): Remove Python version constraint for `importlib-metadata`

---

Makefile
cl_sii/libs/tz_utils.py
mypy.ini
requirements-dev.in
requirements-dev.txt
setup.cfg
tests/test_dte_constants.py
tests/test_dte_data_models.py
tests/test_dte_parse.py
tests/test_libs_csv_utils.py
tests/test_libs_dataclass_utils.py
tests/test_libs_encoding_utils.py
tests/test_libs_io_utils.py
tests/test_libs_mm_utils.py
tests/test_libs_rows_processing.py
tests/test_rcv_constants.py
tests/test_rcv_data_models.py
tests/test_rtc_data_models.py
tests/test_rtc_parse_aec.py

- chore: Move Mypy configuration to separate configuration file.
- chore: Move list of files to be scanned by Mypy to Mypy configuration file.
- chore: Install Python package 'types-pytz'.
- chore: Enable type checking for `pytz`.
- chore: Enable type checking for `signxml`.
- chore: Add missing return type annotations to tests.

Improve type checking

---

.bumpversion.cfg
HISTORY.md
cl_sii/__init__.py

- (PR #446, 2023-03-07) chore(deps-dev): Bump mypy from 0.991 to 1.0.1
- (PR #449, 2023-03-08) Drop support for Python 3.7
- (PR #442, 2023-03-09) chore: Bump actions/cache from 3.2.5 to 3.2.6
- (PR #440, 2023-03-09) fix(cte): Add default values for known missing codes in SII CTE Form 29

Release v0.22.0

---

MANIFEST.in

The file `f29_datos_obj_missing_key_fixes.json` was not being included in the library releases.
Ref: https://cordada.aha.io/requirements/COMPCLDATA-215-1
Ref: https://cordada.aha.io/features/COMPCLDATA-215
Ref: https://github.com/fyntex/lib-cl-sii-python/pull/440

fix(data.cte): Add JSON files to MANIFEST.in

---

cl_sii/data/cte/f29_datos_obj_missing_key_fixes.json

Add codes `156` and `157` to file used by schema validator :func:`cte_f29_datos_schema_best_effort_validator`, since these codes are currently missing in the `tipos` section of the F29 file.
Ref: https://cordada.aha.io/requirements/COMPCLDATA-215-1
Ref: https://cordada.aha.io/features/COMPCLDATA-215
Ref: https://github.com/fyntex/lib-cl-sii-python/pull/440

fix(data.cte): Add missing codes to files used by schema validator

---

.bumpversion.cfg
HISTORY.md
cl_sii/__init__.py

- (PR #427, 2023-03-10) chore(deps-dev): Bump black from 22.12.0 to 23.1.0
- (PR #455, 2023-03-10) fix(data.cte): Add missing codes to files used by schema validator

Release v0.22.2

---

cl_sii/data/cte/f29_datos_obj_missing_key_fixes.json

Add code `8020` to file used by schema validator
:func:`cte_f29_datos_schema_best_effort_validator`,
since this code is currently missing in the `tipos`
and `glosa` sections of the F29 file.
Ref: https://cordada.aha.io/requirements/COMPCLDATA-215-1
Ref: https://cordada.aha.io/features/COMPCLDATA-215
Ref: https://github.com/fyntex/lib-cl-sii-python/pull/440

fix(data.cte): Add missing code `8020` to file used by schema validator

---

.github/workflows/ci.yaml
Makefile
requirements-dev.in
requirements-dev.txt
setup.cfg

> Codecov is the all-in-one code coverage reporting solution for any
> test suite — giving developers actionable insights to deploy reliable
> code with confidence.
- Codecov web site: https://about.codecov.io/
- Documentation: https://docs.codecov.com/
Ref: https://cordada.aha.io/requirements/TECHINFRA-194-8
Ref: https://cordada.aha.io/features/TECHINFRA-194

Add Codecov to CI workflow

---

requirements-dev.txt
requirements.txt

- [Software Repository](https://pypi.org/project/certifi/2023.7.22/)
- [Commits](https://github.com/certifi/python-certifi/compare/2022.06.15...2023.07.22)

chore(deps): Update `certifi` from 2022.6.15 to 2023.7.22

---

.bumpversion.cfg
HISTORY.md
cl_sii/__init__.py

- (PR #478, 2023-04-05) Fix Git alias `lg-github-pr-summary` in Contributing Guidelines
- (PR #479, 2023-04-05) Update code owners for Python dependencies
- (PR #467, 2023-04-10) chore(deps): Bump importlib-metadata from 6.0.0 to 6.1.0
- (PR #483, 2023-04-18) Add Codecov to CI workflow
- (PR #466, 2023-04-18) chore: Bump actions/cache from 3.2.6 to 3.3.1
- (PR #465, 2023-04-18) chore: Bump actions/dependency-review-action from 3.0.3 to 3.0.4
- (PR #481, 2023-04-24) chore: Bump actions/checkout from 3.3.0 to 3.5.2
- (PR #480, 2023-04-24) chore(deps-dev): Bump mypy from 1.0.1 to 1.2.0
- (PR #473, 2023-04-24) chore(deps-dev): Bump types-pytz from 2022.7.1.2 to 2023.3.0.0
- (PR #471, 2023-04-24) chore(deps): Bump pytz from 2022.7.1 to 2023.3
- (PR #468, 2023-04-24) chore(deps): Bump …

Release v0.23.1

---

mypy.ini
setup.py

- Fix incorrect type annotation of `get_version()` in `setup.py`.
- Add missing type annotations to `setup_requirements` and `test_requirements` in `setup.py`.
- Update Mypy configuration to ignore missing imports for `setuptools`.

Fix type checking of Setuptools configuration

---

requirements-dev.txt
requirements.txt

- [Software Repository](https://pypi.org/project/typing-extensions/4.7.1/)
- [Release notes](https://github.com/python/typing_extensions/releases/tag/4.7.1)
- [Changelog](https://github.com/python/typing_extensions/blob/4.7.1/CHANGELOG.md#release-471-july-2-2023)
- [Commits](https://github.com/python/typing_extensions/compare/4.3.0...4.7.1)

chore(deps): Update `typing-extensions` from 4.3.0 to 4.7.1

---

requirements.in
requirements.txt
setup.py
src/cl_sii/dte/data_models.py
src/cl_sii/dte/parse.py
src/cl_sii/rcv/data_models.py
src/cl_sii/rtc/data_models.py
src/cl_sii/rtc/data_models_aec.py
src/cl_sii/rtc/parse_aec.py
src/tests/test_dte_data_models.py
src/tests/test_rcv_data_models.py
src/tests/test_rtc_data_models.py
src/tests/test_rtc_data_models_aec.py

This update switches to `pydantic==2.3.0` but retains the code from the previous version.
Subsequent commits will introduce changes to utilize the features from version 2.
Ref: https://app.shortcut.com/cordada/story/768/update-lib-cl-sii-python
Ref: [sc-768]

Update pydantic from 1.10.12 to 2.3.0

---

src/cl_sii/dte/data_models.py
src/cl_sii/dte/parse.py
src/cl_sii/rcv/data_models.py
src/cl_sii/rtc/data_models.py
src/cl_sii/rtc/data_models_aec.py
src/cl_sii/rtc/parse_aec.py
src/tests/test_dte_data_models.py
src/tests/test_rcv_data_models.py
src/tests/test_rtc_data_models.py
src/tests/test_rtc_data_models_aec.py

Ref: https://app.shortcut.com/cordada/story/768/update-lib-cl-sii-python

Migrate to `pydantic==2.4.2`

---

.github/workflows/ci-cd.yaml
.github/workflows/ci.yaml
.github/workflows/dependency-review.yaml
.github/workflows/git-commit-lint.yaml
.github/workflows/super-linter.yaml

- For jobs that require a cache entry to exist, fail the workflow if the cache entry is not found by setting `fail-on-cache-miss` to `true`.
- Auto-cancel redundant GitHub Actions jobs. Related documentation: https://docs.github.com/en/actions/using-jobs/using-concurrency

Improve CI/CD workflows

---

.bumpversion.cfg
HISTORY.md
src/cl_sii/__init__.py

- (PR #547, 2023-10-02) chore: Bump pydantic from 2.3.0 to 2.4.2
- (PR #544, 2023-10-23) Migrate to `pydantic==2.4.2`
- (PR #545, 2023-10-23) chore: Bump the production-dependencies group with 4 updates
- (PR #549, 2023-10-23) chore: Bump the development-dependencies group with 5 updates
- (PR #553, 2023-10-23) Improve CI/CD workflows
- (PR #554, 2023-10-23) Enable GHA secrets inheritance so that Codecov token can be passed
- (PR #543, 2023-10-23) chore: Bump cryptography from 41.0.3 to 41.0.4
- (PR #551, 2023-10-23) chore: Bump urllib3 from 1.26.12 to 1.26.18

Release v0.23.4

---

src/cl_sii/libs/xml_utils.py
src/cl_sii/rtc/xml_utils.py

Fixes: https://github.com/cordada/lib-cl-sii-python/security/code-scanning/5
Fixes: https://github.com/cordada/lib-cl-sii-python/security/code-scanning/6
Fixes: https://github.com/cordada/lib-cl-sii-python/security/code-scanning/7
Fixes: https://github.com/cordada/lib-cl-sii-python/security/code-scanning/8

Fix GitHub code scanning alerts 'Clear-text logging of sensitive info'

---

src/cl_sii/dte/data_models.py
src/tests/test_dte_data_models.py

* Improved exception message at `.DteXmlData.validate_referencias_numero_linea_ref_order`
* Included Expected an actual value
* Added list of all actual values or `DteXmlData.referencias` in message
Ref: https://app.shortcut.com/cordada/story/1493/

dte: Improve validation error message in `DteXmlData.referencias`

---

Makefile

This task is no longer needed since we are installing `wheel` through dependency manifest files `requirements-dev.in` and `requirements-dev.txt`.

Remove Make task `python-wheel-install`

---

.bumpversion.cfg
HISTORY.md
src/cl_sii/__init__.py

- (PR #555, 2023-10-23) Fix GitHub code scanning alerts 'Clear-text logging of sensitive info'
- (PR #562, 2023-11-03) chore: Bump the production-dependencies group with 2 updates
- (PR #509, 2023-11-06) chore: Bump marshmallow from 3.19.0 to 3.20.1
- (PR #563, 2023-11-06) chore: Bump django from 3.2.20 to 3.2.23
- (PR #561, 2023-11-06) chore: Bump jsonschema from 4.17.3 to 4.19.2
- (PR #558, 2023-11-06) chore: Bump the development-dependencies group with 5 updates
- (PR #559, 2023-11-06) chore: Bump signxml from 3.2.0 to 3.2.1
- (PR #560, 2023-11-06) chore: Bump pytz from 2023.3 to 2023.3.post1
- (PR #557, 2023-11-08) dte: Improve validation error message in `DteXmlData.referencias`
- (PR #564, 2023-11-08) Remove Make task `python-wheel-install`
- (PR #566, 2023-11-08) Add Python project …

Release v0.24.0

---

.bumpversion.cfg
HISTORY.md
src/cl_sii/__init__.py

- (PR #581, 2024-01-03) chore: Bump the production-dependencies group with 4 updates
- (PR #571, 2024-01-03) chore: Bump cryptography from 41.0.4 to 41.0.6
- (PR #580, 2024-01-09) chore: Bump the development-dependencies group with 7 updates
- (PR #583, 2024-01-10) dte: Allow gaps when validating order of `DteXmlData.referencias`
- (PR #579, 2024-01-10) chore: Bump pydantic from 2.4.2 to 2.5.3

Release v0.25.0

---

src/cl_sii/cte/f29/parse_datos_obj.py
src/cl_sii/data/cte/f29_datos_obj_missing_key_fixes.json

- Add code `098` to file used by schema validator
:func:`cte_f29_datos_schema_best_effort_validator`, since this code is currently missing in the `tipos` and `glosa` sections of the F29 file.
- Fixed exception message when the keys of `campos` and `glosa` are different
Ref: https://app.shortcut.com/cordada/story/3852/
Ref: [FD-CL-DATA-230](https://fynpal-com.sentry.io/issues/4907498672/)
Fixes: FD-CL-DATA-230

fix: Add default value for missing code `098` in SII CTE Form 29

---

.bumpversion.cfg
HISTORY.md
src/cl_sii/__init__.py

- (PR #586, 2024-01-30) fix: Add default value for missing code `098` in SII CTE Form 29
- (PR #577, 2024-01-30) chore: Bump cryptography from 41.0.4 to 41.0.7
- (PR #587, 2024-01-30) chore: Bump jsonschema from 4.19.2 to 4.21.1

Release v0.26.0

---

.bumpversion.cfg
HISTORY.md
src/cl_sii/__init__.py

- (PR #593, 2024-02-01) chore: Bump pydantic from 2.5.3 to 2.6.0
- (PR #592, 2024-02-05) chore: Bump lxml from 4.9.2 to 4.9.4
- (PR #595, 2024-02-05) chore: Bump the development-dependencies group with 6 updates
- (PR #596, 2024-02-05) chore: Bump the production-dependencies group with 5 updates
- (PR #599, 2024-02-07) chore: Bump signxml from 3.2.1 to 3.2.2
- (PR #598, 2024-02-07) chore: Bump pydantic from 2.6.0 to 2.6.1
- (PR #600, 2024-02-07) chore: Bump pyopenssl from 23.2.0 to 24.0.0
- (PR #597, 2024-02-07) chore: Bump pytz from 2023.3.post1 to 2024.1
- (PR #601, 2024-02-07) chore: Bump marshmallow from 3.20.1 to 3.20.2
- (PR #602, 2024-02-07) chore(deps): Update `lxml` from 4.9.4 to 5.1.0

Release v0.27.0

---

src/cl_sii/data/cte/f29_datos_obj_missing_key_fixes.json

- Added codes `100` and `103` to file used by schema validator :func:`cte_f29_datos_schema_best_effort_validator`, since this code is currently missing in the `tipos` and `glosa` sections of the F29 file.
Ref: https://app.shortcut.com/cordada/story/4579/
Ref: [FD-CL-DATA-230](https://fynpal-com.sentry.io/issues/4907498672/events/75dc4762a4b9423c9b2a8eb519148634/)
Fixes: FD-CL-DATA-230

fix: Add default value for missing codes in SII CTE Form 29

---

.bumpversion.cfg
HISTORY.md
src/cl_sii/__init__.py

- (PR #606, 2024-02-14) fix: Add default value for missing codes in SII CTE Form 29
- (PR #607, 2024-02-19) chore: Bump cryptography from 41.0.7 to 42.0.2
- (PR #605, 2024-02-19) chore: Bump django from 3.2.23 to 3.2.24
- (PR #608, 2024-02-26) chore: Bump cryptography from 42.0.2 to 42.0.4

Release v0.28.0

---

.bumpversion.cfg
HISTORY.md
src/cl_sii/__init__.py

- (PR #614, 2024-03-26) chore: Bump the production-dependencies group with 4 updates
- (PR #617, 2024-03-27) chore: Bump black from 24.1.1 to 24.3.0
- (PR #619, 2024-03-27) chore: Bump pydantic from 2.6.1 to 2.6.4
- (PR #618, 2024-03-27) chore: Bump marshmallow from 3.20.2 to 3.21.1
- (PR #616, 2024-03-27) chore: Bump django from 3.2.24 to 3.2.25
- (PR #615, 2024-03-27) chore: Bump cryptography from 42.0.4 to 42.0.5
- (PR #620, 2024-03-27) chore: Bump the development-dependencies group with 7 updates
- (PR #621, 2024-04-04) chore: Bump the production-dependencies group with 6 updates
- (PR #628, 2024-04-16) chore: Bump sqlparse from 0.4.4 to 0.5.0
- (PR #627, 2024-04-16) chore: Bump idna from 2.10 to 3.7
- (PR #624, 2024-04-16) chore: Bump pyopenssl from 24.0.0 to 24.1.0
- (PR #629, …

Release v0.29.0

---

requirements-dev.txt
requirements.txt

Update package `zipp` to version 3.19.2 in compiled dependency files
- [Package Manager](https://pypi.org/project/zipp/)
- [Software Repository](https://github.com/jaraco/zipp)
- [Commits](https://github.com/jaraco/zipp/compare/v3.8.1...v3.19.2)
Fixes: https://github.com/cordada/lib-cl-sii-python/security/dependabot/54
Fixes: https://github.com/cordada/lib-cl-sii-python/security/dependabot/55

chore(deps): Update package `zipp` from 3.8.1 to 3.19.2

---

.bumpversion.cfg
HISTORY.md
src/cl_sii/__init__.py

- (PR #640, 2024-05-20) chore: Bump the production-dependencies group across 1 directory with 5 updates
- (PR #643, 2024-05-30) chore: Bump requests from 2.31.0 to 2.32.2
- (PR #642, 2024-05-30) chore: Bump pydantic from 2.6.4 to 2.7.2
- (PR #644, 2024-05-30) chore: Bump the development-dependencies group across 1 directory with 6 updates
- (PR #633, 2024-05-30) chore: Bump jsonschema from 4.21.1 to 4.22.0
- (PR #648, 2024-06-11) Replace hardcoded versions of Pip and others in Make variables
- (PR #649, 2024-06-11) chore: Bump cryptography from 42.0.5 to 42.0.8
- (PR #651, 2024-07-10) chore: Bump urllib3 from 1.26.18 to 1.26.19
- (PR #652, 2024-07-10) chore: Bump djangorestframework from 3.15.1 to 3.15.2
- (PR #655, 2024-07-10) chore(deps): Update package `zipp` from 3.8.1 to 3.19.2
- (PR …

Release v0.30.0

---

src/cl_sii/extras/dj_url_converters.py
src/tests/test_extras_dj_url_converters.py

- Add Django URL path converter for Chilean RUT.
- Add Django URL path converter for Tipo DTE.
- Add tests.
The source code originates from an internal application (see commits 1e0b3617 and 7db9b2b0 of that application’s source code), and was originally written by Jose Tomas Robles Hahn (`RutConverter`) and Felipe Pinto (`TipoDteConverter`).

extras: Add Django URL path converter for RUT and Tipo DTE

---

src/cl_sii/extras/drf_serializers.py
src/tests/test_extras_drf_serializers.py

Use it to extend DRF serializers that inherit from `ModelSerializer` so that Django model fields from `cl_sii.extras.dj_model_fields` do not have to be explicitly defined in the serializer.
The source code originates from an internal application (see commit 3bea7182 of that application’s source code), and was originally written by Jose Tomas Robles Hahn.

extras: Add mapping of Django model fields to DRF serializer fields

---

Makefile
tox.ini

`setup.py test` has been deprecated for years. See:
- https://github.com/pypa/setuptools/issues/1684
- https://github.com/pypa/setuptools/pull/4522
Ref: https://github.com/cordada/lib-cl-sii-python/pull/675

Test coverage broken by migration from `setup.py` to `pyproject.toml`

---

Makefile
pyproject.toml
requirements-dev.in
requirements-dev.txt
setup.cfg

Setuptools has deprecated `python setup.py sdist` and `python setup.py bdist_wheel` in favor of `python -m build`.
This commit replaces the deprecated commands with the new `python -m build` command in `Makefile`, and moves the tool's configuration from `setup.cfg` to `pyproject.toml`.
See also: [How to modernize a `setup.py`` based project?](https://packaging.python.org/en/latest/guides/modernize-setup-py-project/) ([GitHub](https://github.com/pypa/packaging.python.org/blob/afb69f3d/source/guides/modernize-setup-py-project.rst))

Replace `setup.py sdist` and `bdist_wheel` with `build`

---

.bumpversion.cfg
HISTORY.md
src/cl_sii/__init__.py

- (PR #660, 2024-08-23) chore: Bump setuptools from 65.5.1 to 70.3.0
- (PR #672, 2024-08-23) chore: Bump django from 4.2.14 to 4.2.15
- (PR #676, 2024-08-23) chore(deps): Update `pip` from 23.3 to 24.2
- (PR #677, 2024-08-23) chore(deps): Update `wheel` from ≤0.43.0 to 0.44.0
- (PR #675, 2024-08-23) Replace Setuptools Configuration with Python Project Configuration
- (PR #670, 2024-08-23) chore: Bump jsonschema from 4.22.0 to 4.23.0
- (PR #678, 2024-08-23) chore: Bump the development-dependencies group across 1 directory with 7 updates
- (PR #679, 2024-08-23) chore: Bump the production-dependencies group across 1 directory with 2 updates
- (PR #680, 2024-08-23) Test coverage broken by migration from `setup.py` to `pyproject.toml`
- (PR #668, 2024-08-23) chore: Bump pyopenssl from 24.1.0 …

Release v0.32.0

---

pyproject.toml
src/cl_sii/extras/pydantic_types.py
src/tests/test_extras_pydantic_types.py

- Add Pydantic type `cl_sii.extras.pydantic_types.Rut` that can be used in place of `cl_sii.rut.Rut` in Pydantic models and Pydantic data classes.
- Add extra `pydantic` to Python package.
Ref: https://app.shortcut.com/cordada/story/9729 [sc-9729]

extras: Add Pydantic type for `Rut`

---

src/cl_sii/cte/f29/parse_datos_obj.py

Fix the following warning:
> cl_sii/cte/f29/parse_datos_obj.py:31:
> ResourceWarning: unclosed file
> <_io.TextIOWrapper name='cl_sii/data/cte/f29_datos_obj_missing_key_fixes.json' mode='r' encoding='UTF-8'>
> CTE_F29_DATOS_OBJ_MISSING_KEY_FIXES: SiiCteF29DatosObjType = json.load(

cte: Close file object in `f29.parse_datos_obj`

---

.bumpversion.cfg
HISTORY.md
src/cl_sii/__init__.py

- (PR #689, 2024-09-24) chore(deps): Bump pydantic from 2.7.2 to 2.8.2
- (PR #694, 2024-09-24) chore(deps-dev): Bump the development-dependencies group across 1 directory with 4 updates
- (PR #695, 2024-09-24) deps: Update `pydantic` from 2.8.2 to 2.9.2
- (PR #693, 2024-09-24) chore(deps): Bump cryptography from 42.0.8 to 43.0.1
- (PR #696, 2024-09-24) extras: Add Pydantic type for `Rut`
- (PR #687, 2024-09-24) chore: Bump the production-dependencies group with 2 updates
- (PR #697, 2024-09-24) cte: Close file object in `f29.parse_datos_obj`

Release v0.33.0

---

mypy.ini
requirements-dev.in
requirements-dev.txt
src/cl_sii/dte/parse.py
src/cl_sii/libs/xml_utils.py
src/cl_sii/rtc/parse_aec.py

- Install Python package `types-lxml`.
- Update Mypy configuration.
- Fix errors reported by Mypy after enabling type checking for `lxml`.

Enable type checking for `lxml`

---

src/cl_sii/dte/data_models.py
src/cl_sii/rtc/parse_aec.py
src/tests/test_dte_data_models.py

- dte: Relax some DteXmlData validations for trusted inputs
- rtc: Add option to trust the input when parsing AEC XML documents
Ref: https://app.shortcut.com/cordada/story/9837

Relax some validations for trusted inputs

---

.bumpversion.cfg
HISTORY.md
src/cl_sii/__init__.py

- (PR #690, 2024-09-25) chore(deps): Bump lxml from 5.2.2 to 5.3.0
- (PR #691, 2024-09-25) chore(deps): Bump marshmallow from 3.21.3 to 3.22.0
- (PR #701, 2024-09-25) Enable type checking for `setuptools`
- (PR #702, 2024-09-25) Enable type checking for `lxml`
- (PR #703, 2024-09-26) Relax some validations for trusted inputs

Release v0.34.0

---

src/cl_sii/dte/data_models.py
src/cl_sii/dte/parse.py
src/cl_sii/rtc/data_models_aec.py
src/cl_sii/rtc/parse_aec.py
src/tests/test_dte_data_models.py

- dte: Add option to trust the input when parsing DTE XML documents.
- rtc: Fully propagate value of `trust_input` in `parse_aec_xml()`.
Ref: https://github.com/cordada/lib-cl-sii-python/pull/703
Ref: https://app.shortcut.com/cordada/story/9837

Improvements and fixes related to validation of trusted inputs

---

.git-blame-ignore-revs

The file `.git-blame-ignore-revs` contains a list of revisions that are not helpful when assigning blame, such as source code reformatting, Python `import` sorting, etc., so that `git blame` is able to ignore those commits.
See:
- https://git-scm.com/docs/git-blame#Documentation/git-blame.txt---ignore-revs-fileltfilegt
- https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view

Add configuration for ignoring revisions in Git Blame

---

.bumpversion.cfg
HISTORY.md
src/cl_sii/__init__.py

- (PR #715, 2024-10-01) chore: Bump actions/checkout from 4.1.7 to 4.2.0 in the production-dependencies group
- (PR #717, 2024-10-01) Refactor `cryptography.hazmat.*` Python imports
- (PR #716, 2024-10-02) Update cleaning regex to match RUTs with non-numeric digits
- (PR #710, 2024-10-03) chore(deps): Bump tox from 4.20.0 to 4.21.0 in the development-dependencies group
- (PR #711, 2024-10-03) chore(deps): Bump django-filter from 24.2 to 24.3
- (PR #714, 2024-10-03) chore(deps): Bump pytz from 2024.1 to 2024.2
- (PR #712, 2024-10-03) chore(deps): Bump importlib-metadata from 8.4.0 to 8.5.0

Release v0.36.0

---

src/cl_sii/rut/__init__.py
src/tests/test_rut.py

- Improve type annotation of `Rut(value)`. `Rut.__init__()` is able to accept values of type `Rut` by converting them to `str`, so a more appropriate type annotation for `value` is `str | Rut` instead of just `str`.
- Add method `validate_dv()` to `Rut`. This method is useful when we want to validate the DV of a `Rut` that was instantiated with `validate_dv=False`.
- Refactor validation of DV in `Rut.__init__()`.

rut: Improve type annotation; Add method to validate DV

---

src/cl_sii/extras/pydantic_types.py

The regular expression used to validate RUTs in `_RutPydanticAnnotation` results in Pydantic generating an invalid JSON Schema because the regex uses named groups, which are not supported by the JavaScript regular expression syntax used by JSON Schema (and OpenAPI).

extras: Pydantic `Rut` type regex is not compliant with JSON Schema

---

.bumpversion.cfg
HISTORY.md
src/cl_sii/__init__.py

- (PR #721, 2024-10-11) rut: Improve type annotation; Add method to validate DV
- (PR #720, 2024-10-11) chore(deps): Bump django from 4.2.15 to 4.2.16
- (PR #722, 2024-10-25) extras: Pydantic `Rut` type regex is not compliant with JSON Schema

Release v0.37.0

---

.bumpversion.cfg
HISTORY.md
src/cl_sii/__init__.py

- (PR #725, 2024-10-28) extras: Fix generation of JSON Schema for Pydantic `Rut` type
- (PR #726, 2024-10-28) chore(deps): Update `mypy` from 1.11.2 to 1.13.0

Release v0.38.0

---

requirements-dev.txt
requirements.in
requirements.txt

**chore(deps): Update cryptography from 43.0.3 to 44.0.0**
Bumps [cryptography](https://github.com/pyca/cryptography) from 43.0.3 to 44.0.0.
- [Changelog](https://github.com/pyca/cryptography/blob/main/CHANGELOG.rst)
- [Commits](https://github.com/pyca/cryptography/compare/43.0.3...44.0.0)
**chore: Bump pyopenssl from 24.2.1 to 24.3.0**
Bumps [pyopenssl](https://github.com/pyca/pyopenssl) from 24.2.1 to 24.3.0.
- [Changelog](https://github.com/pyca/pyopenssl/blob/main/CHANGELOG.rst)
- [Commits](https://github.com/pyca/pyopenssl/compare/24.2.1...24.3.0)
Ref: https://app.shortcut.com/cordada/story/11838/ [sc-11838]
depends-on: https://github.com/cordada/lib-cl-sii-python/pull/736

deps: Update  cryptography to 44.0.0 and pyopenssl to 24.3.0

---

.bumpversion.cfg
HISTORY.md
src/cl_sii/__init__.py

- (PR #729, 2024-10-30) extras: Fix serialization of `None` in Pydantic `Rut` type
- (PR #730, 2024-11-19) chore: Bump the production-dependencies group with 6 updates
- (PR #733, 2024-11-20) chore: Bump the development-dependencies group across 1 directory with 5 updates
- (PR #734, 2024-12-05) chore: Bump the production-dependencies group with 2 updates
- (PR #732, 2024-12-05) chore(deps): Bump cryptography from 43.0.1 to 43.0.3
- (PR #739, 2024-12-09) chore(deps): Bump pydantic from 2.9.2 to 2.10.3
- (PR #740, 2024-12-09) chore(deps): Bump django from 4.2.16 to 4.2.17
- (PR #736, 2024-12-12) chore(deps): Bump signxml from 3.2.2 to 4.0.3
- (PR #742, 2024-12-12) deps: Update  cryptography to 44.0.0 and pyopenssl to 24.3.0

Release v0.39.0

---

pyproject.toml

Increase minimum version of
- `cryptography`
- `lxml`
- `pyOpenSSL`
to prevent compatibility issues.

deps: Update dependency constraints of Python package `cl-sii`

---

.bumpversion.cfg
HISTORY.md
src/cl_sii/__init__.py

- (PR #748, 2025-01-06) Use most recent patch version of Python in CI/CD configuration
- (PR #750, 2025-01-08) Really use latest patch version of Python in CI/CD configuration
- (PR #751, 2025-01-08) Improve dependency caching in CI/CD configuration
- (PR #749, 2025-01-08) deps: Update dependency constraints of Python package `cl-sii`
- (PR #747, 2025-01-08) chore: Bump the production-dependencies group with 3 updates
- (PR #737, 2025-01-08) chore(deps): Bump setuptools from 70.3.0 to 75.3.0
- (PR #745, 2025-01-08) chore(deps): Bump pydantic from 2.10.3 to 2.10.4
- (PR #746, 2025-01-08) chore(deps): Bump the development-dependencies group with 6 updates

Release v0.40.0

---

mypy.ini

Instead of excluding `src/tests/`, only include individual files.

Exclude only individual test files in Mypy configuration

---

Makefile

This pull request includes updates to the `Makefile` to enhance the cleaning process by standardizing the use of the `RM` variable. The most important changes include replacing direct `rm` commands with `${RM}` and improving the `find` command options for better compatibility and performance.
Enhancements to cleaning process:
* [`Makefile`](diffhunk://#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L48-R65): Replaced direct `rm` commands with `${RM}` to standardize the removal process and ensure consistency across different environments.
* [`Makefile`](diffhunk://#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L48-R65): Improved `find` command options by using `-iname` for case-insensitive matching and `-prune` to optimize directory traversal.

Improve Make tasks `clean-build`, `clean-pyc`, and `clean-test`

---

pyproject.toml
requirements.in
requirements.txt
src/cl_sii/dte/data_models.py
src/cl_sii/rcv/data_models.py
src/cl_sii/rtc/data_models.py
src/cl_sii/rtc/data_models_aec.py

> In general, if something returns `self`, […], you should use `Self` as the return annotation.
> You should not use `Self` as the return annotation if the method is not guaranteed to return an instance of a subclass when the class is subclassed […]

Annotate method return types with `typing.Self` where appropriate

---

pyproject.toml
requirements.in
requirements.txt

Update constraint for optional dependency `Django` from ≥ 2.2.24 to ≥ 4.2 to prevent compatibility issues.
Fixes: https://github.com/cordada/lib-cl-sii-python/security/dependabot/67

deps: Increase minimum version of Python package `Django` to 4.2

---

.bumpversion.cfg
HISTORY.md
src/cl_sii/__init__.py

- (PR #758, 2025-01-15) Enable `warn_unused_ignores` in Mypy configuration
- (PR #759, 2025-01-28) Annotate method return types with `typing.Self` where appropriate
- (PR #761, 2025-01-28) deps: Increase minimum version of Python package `Django` to 4.2
- (PR #760, 2025-01-28) rut: Add constant with lowest RUT for personas jurídicas

Release v0.42.0

---

.github/workflows/ci.yaml

The step *“Check that compiled Python dependency manifests are up-to-date with their sources”* is supposed to run only for the lowest supported Python version (currently 3.8). However, commit 751adb045e99946adb1ea447e4344b4281d65900 from pull request https://github.com/cordada/lib-cl-sii-python/pull/748 inadvertently disabled this step for all Python versions because of an incorrect string comparison (`3.8.` is _not_ a substring of `3.8`).

Python dependency sync check is never executed in CI/CD workflow

---

requirements-dev.txt
requirements.txt

- [Software Repository](https://pypi.org/project/packaging/24.2/)
- [Release Notes](https://github.com/pypa/packaging/releases/tag/24.2)
- [Changelog](https://github.com/pypa/packaging/blob/24.2/CHANGELOG.rst#242---2024-11-08)
- [Commits](https://github.com/pypa/packaging/compare/24.1...24.2)
`packaging` versions <24.2 cause the following error when running `twine check --strict dist/*`:
> Checking `dist/cl_sii-0.43.0-py3-none-any.whl`:
>   ERROR    InvalidDistribution:
>     Invalid distribution metadata: unrecognized or malformed field 'license-file'

deps: Update `packaging` from 24.1 to 24.2

---

.bumpversion.cfg
HISTORY.md
src/cl_sii/__init__.py

- (PR #784, 2025-03-13) chore(deps): Bump the development-dependencies group with 8 updates
- (PR #773, 2025-03-13) chore(deps): Bump django-filter from 24.3 to 25.1
- (PR #774, 2025-03-17) chore(deps): Bump marshmallow from 3.22.0 to 3.26.1
- (PR #776, 2025-03-17) chore(deps): Bump importlib-metadata from 8.5.0 to 8.6.1
- (PR #787, 2025-03-24) Require Python ≥3.9

Release v0.45.0

---

.github/workflows/git-commit-lint.yaml
.github/workflows/task-release-and-deploy.yaml

- Add GitHub Actions workflow to release and deploy.
- Trigger Git Commit Linter when a draft PR is ready for review.
GitHub Actions does not create a new workflow run for events triggered
by the GitHub Actions authentication token (`secrets.GITHUB_TOKEN`),
which results in the Git Commit Linter’s workflow not being triggered
when pull requests are created using GitHub Actions.
This commit adds `ready_for_review` to the event types that trigger the
GitHub Actions workflow 'Git Commit Linter' so that it runs for
pull requests created using GitHub Actions when they are marked as
ready for review by a user.
From [Automatic token authentication](https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication):
> When you use the repository's …

Add GitHub Actions workflow to release and deploy; Etc.

---

requirements-dev.in
requirements-dev.txt

The `pyOpenSSL` package includes type annotations or type stubs since version 24.2.1. We are using `pyOpenSSL` version 25.0.0, so this package is no longer needed.

deps: Uninstall Python package `types-pyOpenSSL`

---

.bumpversion.cfg
HISTORY.md
src/cl_sii/__init__.py

- (PR #790, 2025-03-26) Add GitHub Actions workflow to release and deploy; Etc.
- (PR #792, 2025-04-02) deps: Bump the development-dependencies group with 5 updates
- (PR #794, 2025-04-02) chore(deps): Bump setuptools from 75.3.0 to 78.1.0
- (PR #797, 2025-04-03) chore: Bump the production-dependencies group with 5 updates
- (PR #793, 2025-04-04) chore(deps): Bump djangorestframework from 3.15.2 to 3.16.0
- (PR #795, 2025-04-07) chore(deps): Bump pytz from 2025.1 to 2025.2
- (PR #796, 2025-04-07) chore(deps): Bump pydantic from 2.10.6 to 2.11.2
- (PR #798, 2025-05-06) chore: Bump the production-dependencies group with 3 updates
- (PR #804, 2025-05-14) chore: Bump django from 4.2.20 to 4.2.21
- (PR #805, 2025-05-19) chore: Bump setuptools from 78.1.0 to 78.1.1
- (PR #802, 2025-05-19) …

Release v0.46.0

---

.bumpversion.cfg
HISTORY.md
src/cl_sii/__init__.py

- (PR #809, 2025-05-22) Trigger GitHub Dependency Review when draft pull request is ready for review
- (PR #817, 2025-06-11) chore(deps): Bump django from 4.2.21 to 4.2.22
- (PR #818, 2025-06-11) chore(deps): Bump requests from 2.32.2 to 2.32.4
- (PR #820, 2025-06-30) dte: Generate random `DteNaturalKeys`
- (PR #819, 2025-06-30) chore(deps): Bump urllib3 from 1.26.19 to 2.5.0
- (PR #821, 2025-06-30) Update Dependabot configuration
- (PR #822, 2025-06-30) deps: Update `signxml` from 4.0.3 to 4.0.5
- (PR #812, 2025-06-30) chore(deps): Bump jsonschema from 4.23.0 to 4.24.0
- (PR #814, 2025-06-30) chore(deps): Bump pyopenssl from 25.0.0 to 25.1.0
- (PR #813, 2025-06-30) chore(deps): Bump pydantic from 2.11.2 to 2.11.5
- (PR #826, 2025-06-30) chore(deps): Bump the github-actions-production …

Release v0.47.0

---

requirements-dev.txt
requirements.in
requirements.txt

> Easily download, build, install, upgrade, and uninstall Python packages
- [Web Site](https://setuptools.pypa.io/)
- [VCS Repository](https://github.com/pypa/setuptools.git)
- [Documentation](https://setuptools.pypa.io/)
- [Software Repository](https://pypi.org/project/setuptools/)
**Note**: This package is already installed as a transitive dependency, but it is also a direct dependency (e.g. `setup.py` imports `setuptools`), and direct dependencies should be in `requirements.in` (and `requirements.txt`).

deps: Install Python package `setuptools`

---

pyproject.toml
requirements-dev.in
requirements-dev.txt

From [Wheel's documentation](https://github.com/pypa/wheel/blob/fc8cb416/README.rst):
> ## Historical note
>
> This project used to contain the implementation of the [setuptools](https://pypi.org/project/setuptools/) `bdist_wheel` command, but as of setuptools v70.1, it no longer needs `wheel` installed for that to work. Thus, you should install this **only** if you intend to use the `wheel` command line tool!

deps: Uninstall Python package `wheel`

---

src/cl_sii/rcv/constants.py
src/tests/test_rcv_constants.py

Ref: https://app.shortcut.com/cordada/story/16109/

rcv: Add RcTipoCompra enum to represent "Tipo de Compra" in RCV

---

src/cl_sii/rcv/constants.py
src/tests/test_rcv_constants.py

- Added new types:
- SUPERMERCADOS
- BIENES_RAICES
- ACTIVO_FIJO
- IVA_USO_COMUN
- IVA_NO_RECUPERABLE.
Ref: https://app.shortcut.com/cordada/story/16109/

rcv: Extend RcTipoCompra enum with new purchase types

---

src/cl_sii/rut/constants.py
src/tests/test_rut_constants.py

The value `50000000` is the minimum RUT digits for a "Persona Jurídica", not for the whole range of RUT.
If the minimum RUT digits for a "Persona Jurídica" is desired, use `PERSONA_JURIDICA_MIN_RUT_DIGITS` instead of `RUT_DIGITS_MIN_VALUE`.
⚠️ Breaking change: The range of possible return values of `Rut.random()` will be expanded because it uses `RUT_DIGITS_MIN_VALUE`.
Fixes: https://github.com/cordada/lib-cl-sii-python/issues/96

rut: Constant `RUT_DIGITS_MIN_VALUE` should be for the whole range of RUTs

---

.bumpversion.cfg
HISTORY.md
src/cl_sii/__init__.py

- (PR #850, 2025-08-21) chore(deps): Bump the python-development group across 1 directory with 6 updates
- (PR #856, 2025-08-26) Update Dependabot configuration
- (PR #847, 2025-08-26) chore(deps): Bump jsonschema from 4.24.0 to 4.25.0
- (PR #857, 2025-08-26) Minor improvement of CI workflow
- (PR #858, 2025-08-26) rut: Constant `RUT_DIGITS_MIN_VALUE` should be for the whole range of RUTs
- (PR #859, 2025-08-27) rcv: Enhance "RCV Ventas" CSV parsing and add schema fields

Release v0.52.0

---

src/cl_sii/rcv/parse_csv.py
src/tests/test_rcv_parse_csv.py

This was causing an issue en FD CL DATA that the functions were expecting a `RcvDetalleEntry` instead of a subclass
- Implemented test for `parse_rcv_venta_csv_file` ensuring correct CSV parsing.
- Updated `_RcvCsvRowSchemaBase.preprocess` to handle empty and "-" values correctly.
This is to set as `null` the empty strings

rcv: Update RCV CSV typing and RCV Ventas preprocessing

---

.bumpversion.cfg
HISTORY.md
src/cl_sii/__init__.py

- (PR #862, 2025-08-28) chore(deps): Bump the github-actions-production group with 5 updates
- (PR #864, 2025-08-28) rcv: Expand "RCV Compras" CSV schemas and update field mappings
- (PR #867, 2025-09-02) rcv: Update RCV CSV typing and RCV Ventas preprocessing

Release v0.53.0

---

src/cl_sii/extras/dj_model_fields.py
src/tests/test_extras_dj_model_fields.py

In Django model field `RutField`, add an option to validate that a RUT's "digito verificador" is correct. The option is disabled by default, so it does not break backward compatibility.

extras: Add option to validate RUT DV to Django model field `RutField`

---

src/cl_sii/extras/dj_form_fields.py

Validate "digito verificador" of RUT using `Rut.validate_dv()` instead of `Rut.calc_dv()`.

extras: Refactor `dj_form_fields.RutField.to_python()`

---

.bumpversion.cfg
HISTORY.md
src/cl_sii/__init__.py

- (PR #871, 2025-09-09) rut: Use class variables for exception messages raised by `Rut`
- (PR #873, 2025-09-09) chore(deps): Bump the python-development group across 1 directory with 2 updates
- (PR #874, 2025-09-09) extras: Add option to validate RUT DV to Django model field `RutField`
- (PR #875, 2025-09-09) extras: Refactor `dj_form_fields.RutField.to_python()`
- (PR #872, 2025-09-09) chore(deps): Bump django from 4.2.23 to 4.2.24

Release v0.54.0

---

src/cl_sii/extras/dj_filters.py
src/tests/test_extras_dj_filters.py

This pull request refactors how substring lookups are handled for Chilean RUT fields in Django filters, centralizing logic in the `RutFilter` class and improving test coverage.
The main change is that the selection of the form field class for substring lookups (like `contains` and `icontains`) is now handled within `RutFilter.__init__()`, instead of being managed by a custom `filter_for_lookup()` override in `SiiFilterSet`. This results in cleaner code and more reliable behavior.
Key changes include:
- Refactoring and Logic Centralization:
- Moved the logic for selecting the appropriate `field_class` for substring lookups (`contains`, `icontains`) from `SiiFilterSet.filter_for_lookup()` into the `RutFilter` constructor, ensuring that substring lookups use a plain `CharField` instead of a …

extras: Improve Django filter for `Rut`

---

src/cl_sii/extras/dj_model_fields.py
src/tests/test_extras_dj_model_fields.py

In Django model field `RutField`, when field option `validate_dv` is enabled, the `to_python()` method does not validate the "digito verificador" if the input value is already an instance of `Rut`.
This commit changes the implementation of `to_python()` so that the "digito verificador" is also validated for `Rut` instances when the `validate_dv` field option is enabled.

extras: Django model field `RutField` does not validate DV of `Rut`

---

.bumpversion.cfg
HISTORY.md
src/cl_sii/__init__.py

- (PR #883, 2025-09-10) extras: Add more tests for Django form field for `Rut`
- (PR #884, 2025-09-10) extras: Improve Django filters `FILTER_FOR_DBFIELD_DEFAULTS`
- (PR #882, 2025-09-10) extras: Django model field `RutField` does not validate DV of `Rut`
- (PR #885, 2025-09-10) deps: Update `cryptography` from 45.0.4 to 45.0.7

Release v0.56.0

---

src/cl_sii/cte/data_models.py
src/cl_sii/cte/parsers.py
src/tests/test_cte_parsers.py
src/tests/test_data/sii-cte/cte_empty_f29.html
src/tests/test_data/sii-cte/cte_empty_table.html

- Implemented `parse_taxpayer_data` to parse taxpayer data from CTE HTML.
- Added `TaxpayerData` and `LastFiledDocument` data models.
- Created tests to validate parser functionality with sample HTML input.
Ref: https://app.shortcut.com/cordada/story/16534/

cte: Add parser for "Datos del Contribuyente"

---

src/cl_sii/extras/pydantic_types.py
src/cl_sii/rut/constants.py
src/tests/test_rut_constants.py

Add a regular expression for canonical RUTs that is compatible with JSON Schema and OpenAPI: `cl_sii.rut.constants.RUT_CANONICAL_STRICT_JSON_SCHEMA_REGEX`

rut: Add regex for canonical RUT that is compatible with JSON Schema

---

src/cl_sii/cte/data_models.py
src/cl_sii/cte/parsers.py
src/tests/test_cte_parsers.py
src/tests/test_data/sii-cte/cte_empty_f29.html

- Implemented `parse_taxpayer_properties` to parse property table from CTE HTML.
- Added `Property` and `TaxpayerProperties` data models.
- Created tests to validate parser functionality with sample HTML input.
Ref: https://app.shortcut.com/cordada/story/16536/

cte: Add parser for "Propiedades y Bienes Raíces"

---

.bumpversion.cfg
HISTORY.md
src/cl_sii/__init__.py

- (PR #890, 2025-09-16) cte: Add parser for "Datos del Contribuyente"
- (PR #896, 2025-09-16) rut: Add regex for canonical RUT that is compatible with JSON Schema
- (PR #895, 2025-09-16) cte: Add parser for "Propiedades y Bienes Raíces"

Release v0.58.0
